import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malay Agarwal
 */
public class AddMember extends javax.swing.JFrame {

       /**
        * Creates new form AddMember
        */
       public AddMember() {
              initComponents();
              
              SetIcon();
              MemberNameBox.requestFocusInWindow();
       }

       /**
        * This method is called from within the constructor to initialize the form.
        * WARNING: Do NOT modify this code. The content of this method is always
        * regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              jScrollPane1 = new javax.swing.JScrollPane();
              jLabel1 = new javax.swing.JLabel();
              MemberNumberLabel = new javax.swing.JLabel();
              MemberNumberBox = new javax.swing.JTextField();
              jLabel3 = new javax.swing.JLabel();
              MemberNameBox = new javax.swing.JTextField();
              jLabel4 = new javax.swing.JLabel();
              MemberBirthBox = new javax.swing.JTextField();
              jLabel5 = new javax.swing.JLabel();
              jScrollPane2 = new javax.swing.JScrollPane();
              MemberAddressBox = new javax.swing.JTextArea();
              jLabel6 = new javax.swing.JLabel();
              MemberPhoneBox = new javax.swing.JTextField();
              AddMemberButton = new javax.swing.JButton();
              ClearButton = new javax.swing.JButton();
              MenuButton = new javax.swing.JButton();
              ExitButton = new javax.swing.JButton();
              jLabel7 = new javax.swing.JLabel();
              jLabel2 = new javax.swing.JLabel();
              jMenuBar1 = new javax.swing.JMenuBar();
              jMenu1 = new javax.swing.JMenu();
              AddBookMenuItem = new javax.swing.JMenuItem();
              jSeparator2 = new javax.swing.JPopupMenu.Separator();
              IssueBookMenuItem = new javax.swing.JMenuItem();
              ReturnBookMenuItem = new javax.swing.JMenuItem();
              PurchaseBookMenuItem = new javax.swing.JMenuItem();
              jSeparator3 = new javax.swing.JPopupMenu.Separator();
              SearchBookMenuItem = new javax.swing.JMenuItem();
              jSeparator8 = new javax.swing.JPopupMenu.Separator();
              ViewIssuesMenuItem = new javax.swing.JMenuItem();
              ViewReturnsMenuItem = new javax.swing.JMenuItem();
              ViewPurchasesMenuItem = new javax.swing.JMenuItem();
              jSeparator4 = new javax.swing.JPopupMenu.Separator();
              SearchMemberMenuItem = new javax.swing.JMenuItem();
              jSeparator5 = new javax.swing.JPopupMenu.Separator();
              DeleteBookMenuButton = new javax.swing.JMenuItem();
              DeleteMemberMenuItem = new javax.swing.JMenuItem();
              jSeparator6 = new javax.swing.JPopupMenu.Separator();
              EditBookMenuItem = new javax.swing.JMenuItem();
              EditMemberMenuItem = new javax.swing.JMenuItem();
              jSeparator7 = new javax.swing.JPopupMenu.Separator();
              ViewBooksMenuItem = new javax.swing.JMenuItem();
              ViewMembersMenuItem = new javax.swing.JMenuItem();
              jSeparator1 = new javax.swing.JPopupMenu.Separator();
              ExitMenuItem = new javax.swing.JMenuItem();
              jMenu2 = new javax.swing.JMenu();
              ShortcutsMenuItem = new javax.swing.JMenuItem();
              jSeparator9 = new javax.swing.JPopupMenu.Separator();
              AboutUsMenuItem = new javax.swing.JMenuItem();

              setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
              setTitle("Add member");
              setResizable(false);

              jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
              jLabel1.setText("ADD A MEMBER");

              MemberNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberNumberLabel.setText("Enter member number:");
              MemberNumberLabel.setEnabled(false);

              MemberNumberBox.setEditable(false);
              MemberNumberBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberNumberBox.setEnabled(false);

              jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel3.setText("Enter the name of the member:");

              MemberNameBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberNameBox.setNextFocusableComponent(MemberBirthBox);
              MemberNameBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            MemberNameBoxKeyPressed(evt);
                     }
              });

              jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel4.setText("Enter date of birth (dd/mm/yyyy):");

              MemberBirthBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberBirthBox.setNextFocusableComponent(MemberPhoneBox);
              MemberBirthBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            MemberBirthBoxKeyPressed(evt);
                     }
              });

              jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel5.setText("Enter address:");

              MemberAddressBox.setColumns(20);
              MemberAddressBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberAddressBox.setRows(5);
              MemberAddressBox.setTabSize(0);
              MemberAddressBox.setWrapStyleWord(true);
              MemberAddressBox.setNextFocusableComponent(AddMemberButton);
              MemberAddressBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            MemberAddressBoxKeyPressed(evt);
                     }
              });
              jScrollPane2.setViewportView(MemberAddressBox);

              jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel6.setText("Enter the phone number:");

              MemberPhoneBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberPhoneBox.setNextFocusableComponent(MemberAddressBox);
              MemberPhoneBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            MemberPhoneBoxKeyPressed(evt);
                     }
              });

              AddMemberButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              AddMemberButton.setText("Add member");
              AddMemberButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AddMemberButtonActionPerformed(evt);
                     }
              });

              ClearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ClearButton.setMnemonic('C');
              ClearButton.setText("Clear");
              ClearButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ClearButtonActionPerformed(evt);
                     }
              });

              MenuButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MenuButton.setMnemonic('M');
              MenuButton.setText("Main menu");
              MenuButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            MenuButtonActionPerformed(evt);
                     }
              });

              ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ExitButton.setText("Exit");
              ExitButton.setNextFocusableComponent(MemberNameBox);
              ExitButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ExitButtonActionPerformed(evt);
                     }
              });

              jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel7.setText("The member number will be generated automatically");

              jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel2.setText("Click on Add member button or press enter to add member.");

              jMenu1.setText("Quick Actions");
              jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              AddBookMenuItem.setText("Add a book");
              AddBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AddBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(AddBookMenuItem);
              jMenu1.add(jSeparator2);

              IssueBookMenuItem.setText("Issue a book");
              IssueBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            IssueBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(IssueBookMenuItem);

              ReturnBookMenuItem.setText("Return a book");
              ReturnBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ReturnBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(ReturnBookMenuItem);

              PurchaseBookMenuItem.setText("Purchase a book");
              PurchaseBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            PurchaseBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(PurchaseBookMenuItem);
              jMenu1.add(jSeparator3);

              SearchBookMenuItem.setText("Search for a book");
              SearchBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SearchBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(SearchBookMenuItem);
              jMenu1.add(jSeparator8);

              ViewIssuesMenuItem.setText("View issues");
              ViewIssuesMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewIssuesMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(ViewIssuesMenuItem);

              ViewReturnsMenuItem.setText("View returns");
              ViewReturnsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewReturnsMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(ViewReturnsMenuItem);

              ViewPurchasesMenuItem.setText("View purchases");
              ViewPurchasesMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewPurchasesMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(ViewPurchasesMenuItem);
              jMenu1.add(jSeparator4);

              SearchMemberMenuItem.setText("Search for a member");
              SearchMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SearchMemberMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(SearchMemberMenuItem);
              jMenu1.add(jSeparator5);

              DeleteBookMenuButton.setText("Delete a book");
              DeleteBookMenuButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DeleteBookMenuButtonActionPerformed(evt);
                     }
              });
              jMenu1.add(DeleteBookMenuButton);

              DeleteMemberMenuItem.setText("Delete a member");
              DeleteMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DeleteMemberMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(DeleteMemberMenuItem);
              jMenu1.add(jSeparator6);

              EditBookMenuItem.setText("Edit information of a book");
              EditBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            EditBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(EditBookMenuItem);

              EditMemberMenuItem.setText("Edit information of a member");
              EditMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            EditMemberMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(EditMemberMenuItem);
              jMenu1.add(jSeparator7);

              ViewBooksMenuItem.setText("View all books");
              ViewBooksMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewBooksMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(ViewBooksMenuItem);

              ViewMembersMenuItem.setText("View all members");
              ViewMembersMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewMembersMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(ViewMembersMenuItem);
              jMenu1.add(jSeparator1);

              ExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              ExitMenuItem.setText("Exit");
              ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ExitMenuItemActionPerformed(evt);
                     }
              });
              jMenu1.add(ExitMenuItem);

              jMenuBar1.add(jMenu1);

              jMenu2.setText("Help");
              jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              ShortcutsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              ShortcutsMenuItem.setText("Shortcuts");
              ShortcutsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ShortcutsMenuItemActionPerformed(evt);
                     }
              });
              jMenu2.add(ShortcutsMenuItem);
              jMenu2.add(jSeparator9);

              AboutUsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              AboutUsMenuItem.setText("About us");
              AboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AboutUsMenuItemActionPerformed(evt);
                     }
              });
              jMenu2.add(AboutUsMenuItem);

              jMenuBar1.add(jMenu2);

              setJMenuBar(jMenuBar1);

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                 .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                 .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                                 .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                 .addComponent(MemberNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                 .addComponent(AddMemberButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                               .addComponent(MemberNumberBox, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                                               .addComponent(MemberNameBox)
                                                               .addComponent(MemberBirthBox)
                                                               .addComponent(MemberPhoneBox))
                                                        .addGap(31, 31, 31)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                 .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addGroup(layout.createSequentialGroup()
                                                        .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                   .addComponent(jLabel2))
                            .addGap(0, 34, Short.MAX_VALUE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addComponent(jLabel1)
                                          .addGap(344, 344, 344))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addComponent(jLabel7)
                                          .addContainerGap())))
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(MemberNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(MemberNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                 .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                                 .addComponent(MemberNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                 .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                                 .addComponent(MemberBirthBox, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                                   .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(MemberPhoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGap(55, 55, 55)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(AddMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel7)
                                   .addComponent(jLabel2))
                            .addContainerGap())
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       
       public void GetMemberNumber(){
              
              MemberNumberLabel.setEnabled(true);
              MemberNumberBox.setEnabled(true);
              
              try{
                     
                     Class.forName("com.mysql.jdbc.Driver");
                     Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "password");
                     
                     Statement stmt = con.createStatement();
                     String query = "select COUNT(*) from members;";
                     
                     ResultSet rs = stmt.executeQuery(query);
                     
                     while (rs.next()){
                            
                            int memberNo = rs.getInt(1);
                            MemberNumberBox.setText(Integer.toString(memberNo + 1));
                     }
                     
                     rs.close();
                     stmt.close();
                     con.close();
              }
              catch  (Exception e){
                     
                     JOptionPane.showMessageDialog(null, "A database connection error occured.");
              }
       }
       
       public void Clear(){
              
              MemberNumberLabel.setEnabled(false);
              MemberNumberBox.setEnabled(false);
              
              MemberNumberBox.setText("");
              MemberNameBox.setText("");
              MemberBirthBox.setText("");
              MemberPhoneBox.setText("");
              MemberAddressBox.setText("");     
              
              MemberNameBox.requestFocusInWindow();
       }
       
       
       private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
              Clear();
       }//GEN-LAST:event_ClearButtonActionPerformed

       private void AddMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemberButtonActionPerformed
              if (!MemberNameBox.getText().equals("") && !MemberBirthBox.getText().equals("") && !MemberPhoneBox.getText().equals("") && !MemberAddressBox.getText().equals("")){
                     
                     GetMemberNumber();
                     
                     try{
                            
                            Class.forName("com.mysql.jdbc.Driver");
                            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "password");
                            
                            if (JOptionPane.showConfirmDialog(null, "Are you sure?") == JOptionPane.YES_OPTION){
                                   
                                   String query = "insert into members (memberNo, memberName, address, dob, phone)" + " values (?, ?, ?, ?, ?);";
                                   
                                   String dob = MemberBirthBox.getText().substring(6, 10)+MemberBirthBox.getText().substring(2, 6)+MemberBirthBox.getText(0, 2);
                                   
                                   PreparedStatement stmt = con.prepareStatement(query);
                                   stmt.setString(1, MemberNumberBox.getText());
                                   stmt.setString(2, MemberNameBox.getText());
                                   stmt.setString(3, MemberAddressBox.getText());
                                   stmt.setString(4, dob);
                                   stmt.setString(5, MemberPhoneBox.getText());
                                   stmt.execute();
                                   
                                   JOptionPane.showMessageDialog(null, "Member added successfully!");
                                   
                                   stmt.close();
                            }
                            
                            Clear();
                            con.close();
                     }
                     catch(Exception e){
                            
                            JOptionPane.showMessageDialog(null, "A database connection error occured.");
                     }
              }
              else{
                     JOptionPane.showMessageDialog(null, "One or more than one fields are empty.");
              }
       }//GEN-LAST:event_AddMemberButtonActionPerformed

       private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
              this.setVisible(false);
              MainPage page = new MainPage();
              page.setVisible(true);
       }//GEN-LAST:event_MenuButtonActionPerformed

       private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
             System.exit(0);
       }//GEN-LAST:event_ExitButtonActionPerformed

       private void MemberNameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MemberNameBoxKeyPressed
              if  (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     AddMemberButton.doClick();
              }
       }//GEN-LAST:event_MemberNameBoxKeyPressed

       private void MemberBirthBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MemberBirthBoxKeyPressed
               if  (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     AddMemberButton.doClick();
              }
       }//GEN-LAST:event_MemberBirthBoxKeyPressed

       private void MemberPhoneBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MemberPhoneBoxKeyPressed
               if  (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     AddMemberButton.doClick();
              }
       }//GEN-LAST:event_MemberPhoneBoxKeyPressed

       private void MemberAddressBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MemberAddressBoxKeyPressed
               if  (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     AddMemberButton.doClick();
              }
       }//GEN-LAST:event_MemberAddressBoxKeyPressed

       private void AddBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookMenuItemActionPerformed
              this.setVisible(false);
              AddBook books = new AddBook();
              books.setVisible(true);
       }//GEN-LAST:event_AddBookMenuItemActionPerformed

       private void IssueBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookMenuItemActionPerformed
              this.setVisible(false);
              IssueBook issues = new IssueBook();
              issues.setVisible(true);
       }//GEN-LAST:event_IssueBookMenuItemActionPerformed

       private void ReturnBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookMenuItemActionPerformed
              this.setVisible(false);
              ReturnBook returns = new ReturnBook();
              returns.setVisible(true);
       }//GEN-LAST:event_ReturnBookMenuItemActionPerformed

       private void SearchBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookMenuItemActionPerformed
              this.setVisible(false);
              SearchBook search = new SearchBook();
              search.setVisible(true);
       }//GEN-LAST:event_SearchBookMenuItemActionPerformed

       private void ViewIssuesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewIssuesMenuItemActionPerformed
              this.setVisible(false);
              ViewIssues issues = new ViewIssues();
              issues.setVisible(true);
       }//GEN-LAST:event_ViewIssuesMenuItemActionPerformed

       private void ViewReturnsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReturnsMenuItemActionPerformed
              this.setVisible(false);
              ViewReturns returns = new ViewReturns();
              returns.setVisible(true);
       }//GEN-LAST:event_ViewReturnsMenuItemActionPerformed

       private void ViewPurchasesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPurchasesMenuItemActionPerformed
              this.setVisible(false);
              ViewPurchases purchase = new ViewPurchases();
              purchase.setVisible(true);
       }//GEN-LAST:event_ViewPurchasesMenuItemActionPerformed

       private void SearchMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMemberMenuItemActionPerformed
              this.setVisible(false);
              SearchMember search = new SearchMember();
              search.setVisible(true);
       }//GEN-LAST:event_SearchMemberMenuItemActionPerformed

       private void DeleteBookMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookMenuButtonActionPerformed
              this.setVisible(false);
              DeleteBook deleteBook = new DeleteBook();
              deleteBook.setVisible(true);
       }//GEN-LAST:event_DeleteBookMenuButtonActionPerformed

       private void DeleteMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMemberMenuItemActionPerformed
              this.setVisible(false);
              new DeleteMember().setVisible(true);
       }//GEN-LAST:event_DeleteMemberMenuItemActionPerformed

       private void EditBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBookMenuItemActionPerformed
              this.setVisible(false);
              new EditBook().setVisible(true);
       }//GEN-LAST:event_EditBookMenuItemActionPerformed

       private void EditMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMemberMenuItemActionPerformed
              this.setVisible(false);
              new EditMember().setVisible(true);
       }//GEN-LAST:event_EditMemberMenuItemActionPerformed

       private void ViewBooksMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksMenuItemActionPerformed
              this.setVisible(false);
              new ViewBooks().setVisible(true);
       }//GEN-LAST:event_ViewBooksMenuItemActionPerformed

       private void ViewMembersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMembersMenuItemActionPerformed
              this.setVisible(false);
              new ViewMembers().setVisible(true);
       }//GEN-LAST:event_ViewMembersMenuItemActionPerformed

       private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
              System.exit(0);
       }//GEN-LAST:event_ExitMenuItemActionPerformed

       private void PurchaseBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseBookMenuItemActionPerformed
              this.setVisible(false);
              PurchaseBook purchase = new PurchaseBook();
              purchase.setVisible(true);
       }//GEN-LAST:event_PurchaseBookMenuItemActionPerformed

       private void ShortcutsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortcutsMenuItemActionPerformed
              ShortcutsPage page = new ShortcutsPage();
              page.setVisible(true);
              page.setLocationRelativeTo(this);
       }//GEN-LAST:event_ShortcutsMenuItemActionPerformed

       private void AboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuItemActionPerformed
              AboutUsPage page = new AboutUsPage();
              page.setVisible(true);
              page.setLocationRelativeTo(this);
       }//GEN-LAST:event_AboutUsMenuItemActionPerformed

       /**
        * @param args the command line arguments
        */
       public static void main(String args[]) {
              /* Set the Nimbus look and feel */
              //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
              /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
               */
              try {
                     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Windows".equals(info.getName())) {
                                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                   break;
                            }
                     }
              } catch (ClassNotFoundException ex) {
                     java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                     java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (IllegalAccessException ex) {
                     java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                     java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              }
              //</editor-fold>

              /* Create and display the form */
              java.awt.EventQueue.invokeLater(new Runnable() {
                     public void run() {
                            new AddMember().setVisible(true);
                     }
              });
       }

       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JMenuItem AboutUsMenuItem;
       private javax.swing.JMenuItem AddBookMenuItem;
       private javax.swing.JButton AddMemberButton;
       private javax.swing.JButton ClearButton;
       private javax.swing.JMenuItem DeleteBookMenuButton;
       private javax.swing.JMenuItem DeleteMemberMenuItem;
       private javax.swing.JMenuItem EditBookMenuItem;
       private javax.swing.JMenuItem EditMemberMenuItem;
       private javax.swing.JButton ExitButton;
       private javax.swing.JMenuItem ExitMenuItem;
       private javax.swing.JMenuItem IssueBookMenuItem;
       private javax.swing.JTextArea MemberAddressBox;
       private javax.swing.JTextField MemberBirthBox;
       private javax.swing.JTextField MemberNameBox;
       private javax.swing.JTextField MemberNumberBox;
       private javax.swing.JLabel MemberNumberLabel;
       private javax.swing.JTextField MemberPhoneBox;
       private javax.swing.JButton MenuButton;
       private javax.swing.JMenuItem PurchaseBookMenuItem;
       private javax.swing.JMenuItem ReturnBookMenuItem;
       private javax.swing.JMenuItem SearchBookMenuItem;
       private javax.swing.JMenuItem SearchMemberMenuItem;
       private javax.swing.JMenuItem ShortcutsMenuItem;
       private javax.swing.JMenuItem ViewBooksMenuItem;
       private javax.swing.JMenuItem ViewIssuesMenuItem;
       private javax.swing.JMenuItem ViewMembersMenuItem;
       private javax.swing.JMenuItem ViewPurchasesMenuItem;
       private javax.swing.JMenuItem ViewReturnsMenuItem;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JLabel jLabel2;
       private javax.swing.JLabel jLabel3;
       private javax.swing.JLabel jLabel4;
       private javax.swing.JLabel jLabel5;
       private javax.swing.JLabel jLabel6;
       private javax.swing.JLabel jLabel7;
       private javax.swing.JMenu jMenu1;
       private javax.swing.JMenu jMenu2;
       private javax.swing.JMenuBar jMenuBar1;
       private javax.swing.JScrollPane jScrollPane1;
       private javax.swing.JScrollPane jScrollPane2;
       private javax.swing.JPopupMenu.Separator jSeparator1;
       private javax.swing.JPopupMenu.Separator jSeparator2;
       private javax.swing.JPopupMenu.Separator jSeparator3;
       private javax.swing.JPopupMenu.Separator jSeparator4;
       private javax.swing.JPopupMenu.Separator jSeparator5;
       private javax.swing.JPopupMenu.Separator jSeparator6;
       private javax.swing.JPopupMenu.Separator jSeparator7;
       private javax.swing.JPopupMenu.Separator jSeparator8;
       private javax.swing.JPopupMenu.Separator jSeparator9;
       // End of variables declaration//GEN-END:variables

       private void SetIcon() {
              setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
       }
}
