
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Malay Agarwal
 */
public class IssueBook extends javax.swing.JFrame {

       /**
        * Creates new form IssueBook
        */
       public IssueBook() {
              
              initComponents();
              
              SetIcon();
              
              BookNameBox.requestFocusInWindow();
       }

       /**
        * This method is called from within the constructor to initialize the form.
        * WARNING: Do NOT modify this code. The content of this method is always
        * regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")

       public void SearchBook() {
              int c = 0;
              if (!"".equals(BookNameBox.getText())) {
                     try {
                            Class.forName("com.mysql.jdbc.Driver");
                            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "password");

                            Statement stmt = con.createStatement();

                            String query = "select bookNo, stock, balance from books where bookName = '" + BookNameBox.getText() + "';";

                            ResultSet rs = stmt.executeQuery(query);

                            while (rs.next()) {
                                   c = 1;
                                   if (rs.getInt(3) > 0 && rs.getInt(3) <= rs.getInt(2)) {
                                          
                                          AvailableBalanceBox.setEnabled(true);
                                          AvailableBalanceLabel.setEnabled(true);
                                          
                                          AvailableBalanceBox.setText(Integer.toString(rs.getInt(3)));
                                          
                                          BookNumberLabel.setEnabled(true);
                                          BookNumberBox.setEnabled(true);
                                          BookNumberBox.setText(Integer.toString(rs.getInt(1)));
                                          
                                          MemberNameBox.requestFocusInWindow();
                                   } 
                                   else {
                                          JOptionPane.showMessageDialog(null, "We don't have sufficient copies to issue the book.");
                                          BookNameBox.requestFocusInWindow();
                                   }
                            }

                            if (c == 0) {
                                   JOptionPane.showMessageDialog(null, "This book is not available in the library.");
                                   BookNameBox.requestFocusInWindow();
                            }

                            rs.close();
                            stmt.close();
                            con.close();
                     } 
                     catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Some invalid value has been entered in the book name field.");
                     }
              } 
              else {
                     JOptionPane.showMessageDialog(null, "Please enter a value in the book name field.");
              }
       }

       public void SearchMember() {
              int c = 0;
              if (!MemberNameBox.getText().equals("")) {
                     try {

                            Class.forName("com.mysql.jdbc.Driver");

                            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "password");

                            Statement stmt = con.createStatement();

                            String query = "select memberNo, phone from members where memberName = '" + MemberNameBox.getText() + "';";

                            ResultSet rs = stmt.executeQuery(query);

                            while (rs.next()) {
                                   c = 1;
                                   MemberNumberLabel.setEnabled(true);
                                   MemberPhoneLabel.setEnabled(true);
                                   MemberNumberBox.setEnabled(true);
                                   PhoneBox.setEnabled(true);

                                   MemberNumberBox.setText(Integer.toString(rs.getInt(1)));
                                   PhoneBox.setText(rs.getString(2));
                                   NoOfCopiesBox.requestFocusInWindow();
                                   
                            }

                            if (c == 0) {
                                   JOptionPane.showMessageDialog(null, "This  name is not registered in the library.");
                                   MemberNameBox.requestFocusInWindow();
                            }

                            rs.close();
                            stmt.close();
                            con.close();

                     } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Some invalid value has been entered in the member name field.");
                     }
              }
       }
       
       public void Clear(){
              
              BookNameBox.setText("");
              BookNumberBox.setText("");
              MemberNameBox.setText("");
              MemberNumberBox.setText("");
              PhoneBox.setText("");
              NoOfCopiesBox.setText("");
              DateOfIssueBox.setText("");
              AvailableBalanceBox.setText("");
              
              BookNumberBox.setEnabled(false);
              BookNumberLabel.setEnabled(false);
              MemberNumberBox.setEnabled(false);
              MemberNumberLabel.setEnabled(false);
              PhoneBox.setEnabled(false);
              MemberPhoneLabel.setEnabled(false);
              AvailableBalanceBox.setEnabled(false);
              AvailableBalanceLabel.setEnabled(false);
              
              BookNameBox.requestFocusInWindow();
       }
       
       
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              jLabel1 = new javax.swing.JLabel();
              jLabel2 = new javax.swing.JLabel();
              BookNameBox = new javax.swing.JTextField();
              BookNumberLabel = new javax.swing.JLabel();
              BookNumberBox = new javax.swing.JTextField();
              jLabel4 = new javax.swing.JLabel();
              MemberNameBox = new javax.swing.JTextField();
              MemberNumberLabel = new javax.swing.JLabel();
              MemberNumberBox = new javax.swing.JTextField();
              MemberPhoneLabel = new javax.swing.JLabel();
              PhoneBox = new javax.swing.JTextField();
              jLabel7 = new javax.swing.JLabel();
              NoOfCopiesBox = new javax.swing.JTextField();
              jLabel8 = new javax.swing.JLabel();
              DateOfIssueBox = new javax.swing.JTextField();
              IssueButton = new javax.swing.JButton();
              ClearButton = new javax.swing.JButton();
              MenuButton = new javax.swing.JButton();
              ExitButton = new javax.swing.JButton();
              GetBookNumberButton = new javax.swing.JButton();
              GetMemberNumberButton = new javax.swing.JButton();
              jLabel3 = new javax.swing.JLabel();
              AvailableBalanceLabel = new javax.swing.JLabel();
              AvailableBalanceBox = new javax.swing.JTextField();
              jMenuBar3 = new javax.swing.JMenuBar();
              jMenu3 = new javax.swing.JMenu();
              AddBookMenuItem = new javax.swing.JMenuItem();
              AddMemberMenuItem2 = new javax.swing.JMenuItem();
              jSeparator2 = new javax.swing.JPopupMenu.Separator();
              ReturnBookMenuItem = new javax.swing.JMenuItem();
              PurchaseStockMenuItem = new javax.swing.JMenuItem();
              jSeparator3 = new javax.swing.JPopupMenu.Separator();
              SearchBookMenuItem = new javax.swing.JMenuItem();
              jSeparator8 = new javax.swing.JPopupMenu.Separator();
              ViewIssuesMenuItem = new javax.swing.JMenuItem();
              ViewReturnsMenuItem = new javax.swing.JMenuItem();
              ViewPurchasesMenuItem = new javax.swing.JMenuItem();
              jSeparator4 = new javax.swing.JPopupMenu.Separator();
              SearchMemberMenuItem = new javax.swing.JMenuItem();
              jSeparator5 = new javax.swing.JPopupMenu.Separator();
              DeleteBookMenuItem = new javax.swing.JMenuItem();
              DeleteMemberMenuItem = new javax.swing.JMenuItem();
              jSeparator6 = new javax.swing.JPopupMenu.Separator();
              EditBookMenuItem = new javax.swing.JMenuItem();
              EditMemberMenuItem = new javax.swing.JMenuItem();
              jSeparator7 = new javax.swing.JPopupMenu.Separator();
              ViewBooksMenuItem = new javax.swing.JMenuItem();
              ViewMembersMenuItem = new javax.swing.JMenuItem();
              jSeparator1 = new javax.swing.JPopupMenu.Separator();
              ExitMenuItem = new javax.swing.JMenuItem();
              jMenu4 = new javax.swing.JMenu();
              ShortcutsMenuItem = new javax.swing.JMenuItem();
              jSeparator9 = new javax.swing.JPopupMenu.Separator();
              AboutUsMenuItem = new javax.swing.JMenuItem();

              setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
              setTitle("Issue a book");
              setResizable(false);

              jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
              jLabel1.setText("ISSUE A BOOK");

              jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel2.setText("Enter name of  book:");

              BookNameBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              BookNameBox.setNextFocusableComponent(MemberNameBox);
              BookNameBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            BookNameBoxKeyPressed(evt);
                     }
              });

              BookNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              BookNumberLabel.setText("Book number:");
              BookNumberLabel.setEnabled(false);

              BookNumberBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              BookNumberBox.setEnabled(false);

              jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel4.setText("Enter name of member:");

              MemberNameBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberNameBox.setNextFocusableComponent(NoOfCopiesBox);
              MemberNameBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            MemberNameBoxKeyPressed(evt);
                     }
              });

              MemberNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberNumberLabel.setText("Member number:");
              MemberNumberLabel.setEnabled(false);

              MemberNumberBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberNumberBox.setEnabled(false);

              MemberPhoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberPhoneLabel.setText("Phone number:");
              MemberPhoneLabel.setEnabled(false);

              PhoneBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              PhoneBox.setEnabled(false);

              jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel7.setText("Number of copies:");

              NoOfCopiesBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              NoOfCopiesBox.setNextFocusableComponent(DateOfIssueBox);
              NoOfCopiesBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            NoOfCopiesBoxKeyPressed(evt);
                     }
              });

              jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel8.setText("Date of issue (dd/mm/yyyy):");

              DateOfIssueBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              DateOfIssueBox.setNextFocusableComponent(IssueButton);
              DateOfIssueBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            DateOfIssueBoxKeyPressed(evt);
                     }
              });

              IssueButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              IssueButton.setText("Issue book");
              IssueButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            IssueButtonActionPerformed(evt);
                     }
              });

              ClearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ClearButton.setMnemonic('C');
              ClearButton.setText("Clear");
              ClearButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ClearButtonActionPerformed(evt);
                     }
              });

              MenuButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MenuButton.setMnemonic('M');
              MenuButton.setText("Main menu");
              MenuButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            MenuButtonActionPerformed(evt);
                     }
              });

              ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ExitButton.setText("Exit");
              ExitButton.setNextFocusableComponent(BookNameBox);
              ExitButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ExitButtonActionPerformed(evt);
                     }
              });

              GetBookNumberButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              GetBookNumberButton.setText("Get number");
              GetBookNumberButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            GetBookNumberButtonActionPerformed(evt);
                     }
              });

              GetMemberNumberButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              GetMemberNumberButton.setText("Get number and phone");
              GetMemberNumberButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            GetMemberNumberButtonActionPerformed(evt);
                     }
              });

              jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel3.setText("Please make sure that you click on the get number buttons or press enter after entering names of book and member.");

              AvailableBalanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              AvailableBalanceLabel.setText("Balance available at library:");
              AvailableBalanceLabel.setEnabled(false);

              AvailableBalanceBox.setEditable(false);
              AvailableBalanceBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              AvailableBalanceBox.setEnabled(false);

              jMenu3.setText("Quick Actions");
              jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              AddBookMenuItem.setText("Add a book");
              AddBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AddBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(AddBookMenuItem);

              AddMemberMenuItem2.setText("Add a member");
              AddMemberMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AddMemberMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu3.add(AddMemberMenuItem2);
              jMenu3.add(jSeparator2);

              ReturnBookMenuItem.setText("Return a book");
              ReturnBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ReturnBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(ReturnBookMenuItem);

              PurchaseStockMenuItem.setText("Purchase stock");
              PurchaseStockMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            PurchaseStockMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(PurchaseStockMenuItem);
              jMenu3.add(jSeparator3);

              SearchBookMenuItem.setText("Search for a book");
              SearchBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SearchBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(SearchBookMenuItem);
              jMenu3.add(jSeparator8);

              ViewIssuesMenuItem.setText("View issues");
              ViewIssuesMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewIssuesMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(ViewIssuesMenuItem);

              ViewReturnsMenuItem.setText("View returns");
              ViewReturnsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewReturnsMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(ViewReturnsMenuItem);

              ViewPurchasesMenuItem.setText("View purchases");
              ViewPurchasesMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewPurchasesMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(ViewPurchasesMenuItem);
              jMenu3.add(jSeparator4);

              SearchMemberMenuItem.setText("Search for a member");
              SearchMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SearchMemberMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(SearchMemberMenuItem);
              jMenu3.add(jSeparator5);

              DeleteBookMenuItem.setText("Delete a book");
              DeleteBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DeleteBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(DeleteBookMenuItem);

              DeleteMemberMenuItem.setText("Delete a member");
              DeleteMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DeleteMemberMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(DeleteMemberMenuItem);
              jMenu3.add(jSeparator6);

              EditBookMenuItem.setText("Edit information of a book");
              EditBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            EditBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(EditBookMenuItem);

              EditMemberMenuItem.setText("Edit information of a member");
              EditMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            EditMemberMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(EditMemberMenuItem);
              jMenu3.add(jSeparator7);

              ViewBooksMenuItem.setText("View all books");
              ViewBooksMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewBooksMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(ViewBooksMenuItem);

              ViewMembersMenuItem.setText("View all members");
              ViewMembersMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewMembersMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(ViewMembersMenuItem);
              jMenu3.add(jSeparator1);

              ExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              ExitMenuItem.setText("Exit");
              ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ExitMenuItemActionPerformed(evt);
                     }
              });
              jMenu3.add(ExitMenuItem);

              jMenuBar3.add(jMenu3);

              jMenu4.setText("Help");
              jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              ShortcutsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              ShortcutsMenuItem.setText("Shortcuts");
              ShortcutsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ShortcutsMenuItemActionPerformed(evt);
                     }
              });
              jMenu4.add(ShortcutsMenuItem);
              jMenu4.add(jSeparator9);

              AboutUsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              AboutUsMenuItem.setText("About us");
              AboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AboutUsMenuItemActionPerformed(evt);
                     }
              });
              jMenu4.add(AboutUsMenuItem);

              jMenuBar3.add(jMenu4);

              setJMenuBar(jMenuBar3);

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(IssueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                          .addComponent(MemberNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(BookNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(125, 125, 125))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                 .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 70, Short.MAX_VALUE)
                                                        .addComponent(jLabel3))
                                                 .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                               .addComponent(BookNameBox)
                                                               .addComponent(MemberNameBox)
                                                               .addComponent(MemberNumberBox, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                               .addComponent(BookNumberBox))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addComponent(GetBookNumberButton)
                                                               .addComponent(GetMemberNumberButton))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                               .addComponent(AvailableBalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                               .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                               .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                               .addComponent(MemberPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                               .addComponent(PhoneBox)
                                                               .addComponent(NoOfCopiesBox)
                                                               .addComponent(DateOfIssueBox, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                                               .addComponent(AvailableBalanceBox))))
                                          .addGap(34, 34, 34))))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(411, 411, 411))
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(0, 26, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                 .addComponent(BookNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                                 .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                               .addComponent(BookNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                               .addComponent(BookNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(5, 5, 5)
                                                        .addComponent(GetBookNumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(MemberNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                 .addComponent(PhoneBox, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                                 .addComponent(MemberPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(NoOfCopiesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(DateOfIssueBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(MemberNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(MemberNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(GetMemberNumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(AvailableBalanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(AvailableBalanceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(IssueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(78, 78, 78)
                            .addComponent(jLabel3)
                            .addContainerGap())
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void IssueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueButtonActionPerformed
              if (!BookNameBox.getText().equals("") && !MemberNameBox.getText().equals("") && !NoOfCopiesBox.getText().equals("") && !DateOfIssueBox.getText().equals("")){
              
                     try {

                            Class.forName("com.mysql.jdbc.Driver");

                            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "password");

                            if (JOptionPane.showConfirmDialog(null, "Are you sure?") == JOptionPane.YES_OPTION) {

                                   String query1 = "insert into issues (bookNo, bookName, memberNo, memberName, phone, noOfCopies, dateOfIssue, leftCopies)" + "values (?, ?, ?, ?, ?, ?, ?, ?);";

                                   String doi = DateOfIssueBox.getText().substring(6, 10) + DateOfIssueBox.getText().substring(2, 6) + DateOfIssueBox.getText().substring(0, 2);

                                   PreparedStatement stmt = con.prepareStatement(query1);
                                   stmt.setString(1, BookNumberBox.getText());
                                   stmt.setString(2, BookNameBox.getText());
                                   stmt.setString(3, MemberNumberBox.getText());
                                   stmt.setString(4, MemberNameBox.getText());
                                   stmt.setString(5, PhoneBox.getText());
                                   stmt.setString(6, NoOfCopiesBox.getText());
                                   stmt.setString(7, doi);
                                   stmt.setString(8, NoOfCopiesBox.getText());

                                   stmt.execute();

                                   Statement stmt2 = con.createStatement();
                                   String query2 = "update books set balance = balance-" + NoOfCopiesBox.getText() + " where bookNo = " + BookNumberBox.getText() + ";";
                                   stmt2.executeUpdate(query2);

                                   JOptionPane.showMessageDialog(null, "Book issued successfully!");
                            
                                   stmt.close();
                                   stmt2.close();
                            } 
                     
                     Clear();
                     con.close();
                     } 
                     catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "A database connection error occured.");
                     }
              }
              else{
                     
                     JOptionPane.showMessageDialog(null, "One or more than one fields are empty.");
              }
       }//GEN-LAST:event_IssueButtonActionPerformed

       private void GetBookNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetBookNumberButtonActionPerformed
              SearchBook();
              //MemberNameBox.requestFocusInWindow();
       }//GEN-LAST:event_GetBookNumberButtonActionPerformed

       private void GetMemberNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetMemberNumberButtonActionPerformed
              SearchMember();
              //NoOfCopiesBox.requestFocusInWindow();
       }//GEN-LAST:event_GetMemberNumberButtonActionPerformed

       private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
              Clear();
       }//GEN-LAST:event_ClearButtonActionPerformed

       private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
              this.setVisible(false);
              MainPage page = new MainPage();
              page.setVisible(true);
       }//GEN-LAST:event_MenuButtonActionPerformed

       private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
              System.exit(0);
       }//GEN-LAST:event_ExitButtonActionPerformed

       private void BookNameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BookNameBoxKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     GetBookNumberButton.doClick();
              }
       }//GEN-LAST:event_BookNameBoxKeyPressed

       private void MemberNameBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MemberNameBoxKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     GetMemberNumberButton.doClick();
              }
       }//GEN-LAST:event_MemberNameBoxKeyPressed

       private void NoOfCopiesBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoOfCopiesBoxKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     IssueButton.doClick();
              }
       }//GEN-LAST:event_NoOfCopiesBoxKeyPressed

       private void DateOfIssueBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateOfIssueBoxKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     IssueButton.doClick();
              }
       }//GEN-LAST:event_DateOfIssueBoxKeyPressed

       private void AddBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookMenuItemActionPerformed
              this.setVisible(false);
              AddBook books = new AddBook();
              books.setVisible(true);
       }//GEN-LAST:event_AddBookMenuItemActionPerformed

       private void AddMemberMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemberMenuItem2ActionPerformed
              this.setVisible(false);
              AddMember member = new AddMember();
              member.setVisible(true);
       }//GEN-LAST:event_AddMemberMenuItem2ActionPerformed

       private void ReturnBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookMenuItemActionPerformed
              this.setVisible(false);
              ReturnBook returns = new ReturnBook();
              returns.setVisible(true);
       }//GEN-LAST:event_ReturnBookMenuItemActionPerformed

       private void PurchaseStockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseStockMenuItemActionPerformed
              this.setVisible(false);
              PurchaseBook purchase = new PurchaseBook();
              purchase.setVisible(true);
       }//GEN-LAST:event_PurchaseStockMenuItemActionPerformed

       private void SearchBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookMenuItemActionPerformed
              this.setVisible(false);
              SearchBook search = new SearchBook();
              search.setVisible(true);
       }//GEN-LAST:event_SearchBookMenuItemActionPerformed

       private void ViewReturnsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReturnsMenuItemActionPerformed
              this.setVisible(false);
              ViewReturns returns = new ViewReturns();
              returns.setVisible(true);
       }//GEN-LAST:event_ViewReturnsMenuItemActionPerformed

       private void ViewPurchasesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPurchasesMenuItemActionPerformed
              this.setVisible(false);
              ViewPurchases purchase = new ViewPurchases();
              purchase.setVisible(true);
       }//GEN-LAST:event_ViewPurchasesMenuItemActionPerformed

       private void SearchMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMemberMenuItemActionPerformed
              this.setVisible(false);
              SearchMember search = new SearchMember();
              search.setVisible(true);
       }//GEN-LAST:event_SearchMemberMenuItemActionPerformed

       private void DeleteMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMemberMenuItemActionPerformed
              this.setVisible(false);
              new DeleteMember().setVisible(true);
       }//GEN-LAST:event_DeleteMemberMenuItemActionPerformed

       private void EditBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBookMenuItemActionPerformed
              this.setVisible(false);
              new EditBook().setVisible(true);
       }//GEN-LAST:event_EditBookMenuItemActionPerformed

       private void EditMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMemberMenuItemActionPerformed
              this.setVisible(false);
              new EditMember().setVisible(true);
       }//GEN-LAST:event_EditMemberMenuItemActionPerformed

       private void ViewBooksMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksMenuItemActionPerformed
              this.setVisible(false);
              new ViewBooks().setVisible(true);
       }//GEN-LAST:event_ViewBooksMenuItemActionPerformed

       private void ViewMembersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMembersMenuItemActionPerformed
              this.setVisible(false);
              new ViewMembers().setVisible(true);
       }//GEN-LAST:event_ViewMembersMenuItemActionPerformed

       private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
              System.exit(0);
       }//GEN-LAST:event_ExitMenuItemActionPerformed

       private void ViewIssuesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewIssuesMenuItemActionPerformed
              this.setVisible(false);
              ViewIssues issues = new ViewIssues();
              issues.setVisible(true);
       }//GEN-LAST:event_ViewIssuesMenuItemActionPerformed

       private void DeleteBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookMenuItemActionPerformed
              this.setVisible(false);
              IssueBook issues = new IssueBook();
              issues.setVisible(true);
       }//GEN-LAST:event_DeleteBookMenuItemActionPerformed

       private void AboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuItemActionPerformed
              AboutUsPage page = new AboutUsPage();
              page.setVisible(true);
              page.setLocationRelativeTo(this);
       }//GEN-LAST:event_AboutUsMenuItemActionPerformed

       private void ShortcutsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortcutsMenuItemActionPerformed
              ShortcutsPage page = new ShortcutsPage();
              page.setVisible(true);
              page.setLocationRelativeTo(this);
       }//GEN-LAST:event_ShortcutsMenuItemActionPerformed

       /**
        * @param args the command line arguments
        */
       public static void main(String args[]) {
              /* Set the Nimbus look and feel */
              //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
              /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
               */
              try {
                     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Windows".equals(info.getName())) {
                                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                   break;
                            }
                     }
              } catch (ClassNotFoundException ex) {
                     java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                     java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (IllegalAccessException ex) {
                     java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                     java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              }
              //</editor-fold>

              /* Create and display the form */
              java.awt.EventQueue.invokeLater(new Runnable() {
                     public void run() {
                            new IssueBook().setVisible(true);
                     }
              });
       }

       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JMenuItem AboutUsMenuItem;
       private javax.swing.JMenuItem AddBookMenuItem;
       private javax.swing.JMenuItem AddMemberMenuItem2;
       private javax.swing.JTextField AvailableBalanceBox;
       private javax.swing.JLabel AvailableBalanceLabel;
       private javax.swing.JTextField BookNameBox;
       private javax.swing.JTextField BookNumberBox;
       private javax.swing.JLabel BookNumberLabel;
       private javax.swing.JButton ClearButton;
       private javax.swing.JTextField DateOfIssueBox;
       private javax.swing.JMenuItem DeleteBookMenuItem;
       private javax.swing.JMenuItem DeleteMemberMenuItem;
       private javax.swing.JMenuItem EditBookMenuItem;
       private javax.swing.JMenuItem EditMemberMenuItem;
       private javax.swing.JButton ExitButton;
       private javax.swing.JMenuItem ExitMenuItem;
       private javax.swing.JButton GetBookNumberButton;
       private javax.swing.JButton GetMemberNumberButton;
       private javax.swing.JButton IssueButton;
       private javax.swing.JTextField MemberNameBox;
       private javax.swing.JTextField MemberNumberBox;
       private javax.swing.JLabel MemberNumberLabel;
       private javax.swing.JLabel MemberPhoneLabel;
       private javax.swing.JButton MenuButton;
       private javax.swing.JTextField NoOfCopiesBox;
       private javax.swing.JTextField PhoneBox;
       private javax.swing.JMenuItem PurchaseStockMenuItem;
       private javax.swing.JMenuItem ReturnBookMenuItem;
       private javax.swing.JMenuItem SearchBookMenuItem;
       private javax.swing.JMenuItem SearchMemberMenuItem;
       private javax.swing.JMenuItem ShortcutsMenuItem;
       private javax.swing.JMenuItem ViewBooksMenuItem;
       private javax.swing.JMenuItem ViewIssuesMenuItem;
       private javax.swing.JMenuItem ViewMembersMenuItem;
       private javax.swing.JMenuItem ViewPurchasesMenuItem;
       private javax.swing.JMenuItem ViewReturnsMenuItem;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JLabel jLabel2;
       private javax.swing.JLabel jLabel3;
       private javax.swing.JLabel jLabel4;
       private javax.swing.JLabel jLabel7;
       private javax.swing.JLabel jLabel8;
       private javax.swing.JMenu jMenu3;
       private javax.swing.JMenu jMenu4;
       private javax.swing.JMenuBar jMenuBar3;
       private javax.swing.JPopupMenu.Separator jSeparator1;
       private javax.swing.JPopupMenu.Separator jSeparator2;
       private javax.swing.JPopupMenu.Separator jSeparator3;
       private javax.swing.JPopupMenu.Separator jSeparator4;
       private javax.swing.JPopupMenu.Separator jSeparator5;
       private javax.swing.JPopupMenu.Separator jSeparator6;
       private javax.swing.JPopupMenu.Separator jSeparator7;
       private javax.swing.JPopupMenu.Separator jSeparator8;
       private javax.swing.JPopupMenu.Separator jSeparator9;
       // End of variables declaration//GEN-END:variables

       private void SetIcon() {
              
              setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
       }
}
