import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malay Agarwal
 */
public class ShortcutsPage extends javax.swing.JFrame {

       /**
        * Creates new form ShortcutsPage
        */
       public ShortcutsPage() {
              
              initComponents();
              
              SetIcon();
       }

       /**
        * This method is called from within the constructor to initialize the form.
        * WARNING: Do NOT modify this code. The content of this method is always
        * regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              jLabel1 = new javax.swing.JLabel();
              jLabel2 = new javax.swing.JLabel();
              jLabel3 = new javax.swing.JLabel();
              jLabel4 = new javax.swing.JLabel();
              jLabel5 = new javax.swing.JLabel();
              jLabel6 = new javax.swing.JLabel();
              jLabel7 = new javax.swing.JLabel();
              jLabel8 = new javax.swing.JLabel();
              jLabel9 = new javax.swing.JLabel();
              jLabel10 = new javax.swing.JLabel();
              jLabel11 = new javax.swing.JLabel();
              jLabel12 = new javax.swing.JLabel();
              jLabel13 = new javax.swing.JLabel();
              jLabel14 = new javax.swing.JLabel();
              jLabel17 = new javax.swing.JLabel();
              jLabel15 = new javax.swing.JLabel();
              jLabel16 = new javax.swing.JLabel();
              jLabel18 = new javax.swing.JLabel();

              setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
              setTitle("Shortcuts");
              setResizable(false);

              jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel1.setText("Enter key:");

              jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel2.setText("Execute actions of various buttons.");

              jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel3.setText("Ctrl+Shift+A:");

              jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel4.setText("Opens the abouts us page.");

              jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel5.setText("Ctrl+Shift+S:");

              jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel6.setText("Opens the shortcuts (this) page.");

              jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel7.setText("Ctrl+Alt+E:");

              jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel8.setText("Exits the current window.");

              jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel9.setText("Tab key:");

              jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel10.setText("Jump between textfields and buttons.");

              jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel11.setText("Alt+M:");

              jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel12.setText("Go to the main menu.");

              jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel13.setText("Alt+C:");

              jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel14.setText("Clear textfields.");

              jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel17.setText("Insert key:");

              jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel15.setText("Opens the edit page in View Books and View Members pages.");

              jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
              jLabel16.setText("Delete key:");

              jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel18.setText("Opens the delete page in View Books and View Members pages.");

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                          .addGroup(layout.createSequentialGroup()
                                                 .addComponent(jLabel1)
                                                 .addGap(18, 18, 18)
                                                 .addComponent(jLabel2))
                                          .addGroup(layout.createSequentialGroup()
                                                 .addComponent(jLabel3)
                                                 .addGap(18, 18, 18)
                                                 .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel5)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabel6))
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel7)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabel8))
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel9)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabel10))
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel11)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabel12))
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel13)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabel14))
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel17)
                                          .addGap(18, 18, 18)
                                          .addComponent(jLabel15))
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel16)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addComponent(jLabel18)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                   .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       /**
        * @param args the command line arguments
        */
       public static void main(String args[]) {
              /* Set the Nimbus look and feel */
              //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
              /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
               */
              try {
                     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Nimbus".equals(info.getName())) {
                                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                   break;
                            }
                     }
              } catch (ClassNotFoundException ex) {
                     java.util.logging.Logger.getLogger(ShortcutsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                     java.util.logging.Logger.getLogger(ShortcutsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (IllegalAccessException ex) {
                     java.util.logging.Logger.getLogger(ShortcutsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                     java.util.logging.Logger.getLogger(ShortcutsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              }
              //</editor-fold>

              /* Create and display the form */
              java.awt.EventQueue.invokeLater(new Runnable() {
                     public void run() {
                            new ShortcutsPage().setVisible(true);
                     }
              });
       }

       private void SetIcon() {
              
              setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
       }

       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JLabel jLabel1;
       private javax.swing.JLabel jLabel10;
       private javax.swing.JLabel jLabel11;
       private javax.swing.JLabel jLabel12;
       private javax.swing.JLabel jLabel13;
       private javax.swing.JLabel jLabel14;
       private javax.swing.JLabel jLabel15;
       private javax.swing.JLabel jLabel16;
       private javax.swing.JLabel jLabel17;
       private javax.swing.JLabel jLabel18;
       private javax.swing.JLabel jLabel2;
       private javax.swing.JLabel jLabel3;
       private javax.swing.JLabel jLabel4;
       private javax.swing.JLabel jLabel5;
       private javax.swing.JLabel jLabel6;
       private javax.swing.JLabel jLabel7;
       private javax.swing.JLabel jLabel8;
       private javax.swing.JLabel jLabel9;
       // End of variables declaration//GEN-END:variables
}
