import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malay Agarwal
 */
public class ViewIssues extends javax.swing.JFrame {

       /**
        * Creates new form ViewIssues
        */
       public ViewIssues() {
              initComponents();
              
              SetIcon();
              TotalCopiesLabel.setVisible(false);
              TotalCopiesBox.setVisible(false);
       }

       /**
        * This method is called from within the constructor to initialize the form.
        * WARNING: Do NOT modify this code. The content of this method is always
        * regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              buttonGroup1 = new javax.swing.ButtonGroup();
              jLabel1 = new javax.swing.JLabel();
              DateLabel = new javax.swing.JLabel();
              DateBox = new javax.swing.JTextField();
              SearchTermLabel = new javax.swing.JLabel();
              SearchTermBox = new javax.swing.JTextField();
              GetIssuesButton = new javax.swing.JButton();
              ClearButton = new javax.swing.JButton();
              DateRadioButton = new javax.swing.JRadioButton();
              BookNameRadioButton = new javax.swing.JRadioButton();
              MemberNameRadioButton = new javax.swing.JRadioButton();
              TotalCopiesLabel = new javax.swing.JLabel();
              TotalCopiesBox = new javax.swing.JTextField();
              jScrollPane1 = new javax.swing.JScrollPane();
              ResultTable = new javax.swing.JTable();
              MenuButton = new javax.swing.JButton();
              ExitButton = new javax.swing.JButton();
              jLabel2 = new javax.swing.JLabel();
              GroupByCombo = new javax.swing.JComboBox<>();
              jLabel3 = new javax.swing.JLabel();
              jLabel4 = new javax.swing.JLabel();
              jMenuBar4 = new javax.swing.JMenuBar();
              jMenu6 = new javax.swing.JMenu();
              AddBookMenuItem3 = new javax.swing.JMenuItem();
              AddMemberMenuItem2 = new javax.swing.JMenuItem();
              jSeparator19 = new javax.swing.JPopupMenu.Separator();
              IssueBookMenuItem2 = new javax.swing.JMenuItem();
              ReturnBookMenuItem2 = new javax.swing.JMenuItem();
              PurchaseBookMenuItem = new javax.swing.JMenuItem();
              jSeparator21 = new javax.swing.JPopupMenu.Separator();
              SearchBookMenuItem = new javax.swing.JMenuItem();
              jSeparator24 = new javax.swing.JPopupMenu.Separator();
              ViewReturnsMenuItem2 = new javax.swing.JMenuItem();
              ViewPurchasesMenuItem2 = new javax.swing.JMenuItem();
              jSeparator22 = new javax.swing.JPopupMenu.Separator();
              SearchMemberMenuItem = new javax.swing.JMenuItem();
              jSeparator2 = new javax.swing.JPopupMenu.Separator();
              DeleteBookMenuButton2 = new javax.swing.JMenuItem();
              DeleteMemberMenuItem2 = new javax.swing.JMenuItem();
              jSeparator1 = new javax.swing.JPopupMenu.Separator();
              EditBookMenuItem2 = new javax.swing.JMenuItem();
              EditMemberMenuItem2 = new javax.swing.JMenuItem();
              jSeparator25 = new javax.swing.JPopupMenu.Separator();
              ViewBooksMenuItem2 = new javax.swing.JMenuItem();
              ViewMembersMenuItem2 = new javax.swing.JMenuItem();
              jSeparator26 = new javax.swing.JPopupMenu.Separator();
              ExitMenuItem2 = new javax.swing.JMenuItem();
              jMenu7 = new javax.swing.JMenu();
              ShortcutsMenuItem = new javax.swing.JMenuItem();
              jSeparator27 = new javax.swing.JPopupMenu.Separator();
              AboutUsMenuItem = new javax.swing.JMenuItem();

              setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
              setTitle("View issues");
              setResizable(false);

              jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
              jLabel1.setText("VIEW ISSUES");

              DateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              DateLabel.setText("Enter date (dd/mm/yyyy):");
              DateLabel.setEnabled(false);

              DateBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              DateBox.setEnabled(false);
              DateBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            DateBoxKeyPressed(evt);
                     }
              });

              SearchTermLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              SearchTermLabel.setText("Enter search term:");
              SearchTermLabel.setEnabled(false);

              SearchTermBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              SearchTermBox.setEnabled(false);
              SearchTermBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            SearchTermBoxKeyPressed(evt);
                     }
              });

              GetIssuesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              GetIssuesButton.setText("Get issues");
              GetIssuesButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            GetIssuesButtonActionPerformed(evt);
                     }
              });

              ClearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ClearButton.setMnemonic('C');
              ClearButton.setText("Clear");
              ClearButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ClearButtonActionPerformed(evt);
                     }
              });

              buttonGroup1.add(DateRadioButton);
              DateRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              DateRadioButton.setText("Get issues by date");
              DateRadioButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DateRadioButtonActionPerformed(evt);
                     }
              });

              buttonGroup1.add(BookNameRadioButton);
              BookNameRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              BookNameRadioButton.setText("Get issues by book name");
              BookNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            BookNameRadioButtonActionPerformed(evt);
                     }
              });

              buttonGroup1.add(MemberNameRadioButton);
              MemberNameRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MemberNameRadioButton.setText("Get issues by member name");
              MemberNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            MemberNameRadioButtonActionPerformed(evt);
                     }
              });

              TotalCopiesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              TotalCopiesLabel.setText("TotalCopiesLabel");

              TotalCopiesBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              ResultTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ResultTable.setModel(new javax.swing.table.DefaultTableModel(
                     new Object [][] {

                     },
                     new String [] {
                            "Book Number", "Book Name", "Member Number", "Member Name", "Date of Issue", "No of Copies"
                     }
              ) {
                     boolean[] canEdit = new boolean [] {
                            false, false, false, false, false, false
                     };

                     public boolean isCellEditable(int rowIndex, int columnIndex) {
                            return canEdit [columnIndex];
                     }
              });
              ResultTable.getTableHeader().setReorderingAllowed(false);
              jScrollPane1.setViewportView(ResultTable);
              if (ResultTable.getColumnModel().getColumnCount() > 0) {
                     ResultTable.getColumnModel().getColumn(5).setResizable(false);
              }

              MenuButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MenuButton.setMnemonic('M');
              MenuButton.setText("Main menu");
              MenuButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            MenuButtonActionPerformed(evt);
                     }
              });

              ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ExitButton.setText("Exit");
              ExitButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ExitButtonActionPerformed(evt);
                     }
              });

              jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel2.setText("Sort by:");

              GroupByCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              GroupByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default (Book Number)", "Book Name", "Member Number", "Member Name", "No. of Copies", "Date of Issue" }));
              GroupByCombo.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            GroupByComboActionPerformed(evt);
                     }
              });
              GroupByCombo.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            GroupByComboKeyPressed(evt);
                     }
              });

              jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel3.setText("After selecting a sort criteria, please click on the Get issues button or press enter.");

              jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel4.setText("After entering a value in the box, click on the Get issues button or press enter.");

              jMenu6.setText("Quick Actions");
              jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              AddBookMenuItem3.setText("Add a book");
              AddBookMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AddBookMenuItem3ActionPerformed(evt);
                     }
              });
              jMenu6.add(AddBookMenuItem3);

              AddMemberMenuItem2.setText("Add a member");
              AddMemberMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AddMemberMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(AddMemberMenuItem2);
              jMenu6.add(jSeparator19);

              IssueBookMenuItem2.setText("Issue a book");
              IssueBookMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            IssueBookMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(IssueBookMenuItem2);

              ReturnBookMenuItem2.setText("Return a book");
              ReturnBookMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ReturnBookMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ReturnBookMenuItem2);

              PurchaseBookMenuItem.setText("Purchase a book");
              PurchaseBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            PurchaseBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu6.add(PurchaseBookMenuItem);
              jMenu6.add(jSeparator21);

              SearchBookMenuItem.setText("Search for a book");
              SearchBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SearchBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu6.add(SearchBookMenuItem);
              jMenu6.add(jSeparator24);

              ViewReturnsMenuItem2.setText("View returns");
              ViewReturnsMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewReturnsMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ViewReturnsMenuItem2);

              ViewPurchasesMenuItem2.setText("View purchases");
              ViewPurchasesMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewPurchasesMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ViewPurchasesMenuItem2);
              jMenu6.add(jSeparator22);

              SearchMemberMenuItem.setText("Search for a member");
              SearchMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SearchMemberMenuItemActionPerformed(evt);
                     }
              });
              jMenu6.add(SearchMemberMenuItem);
              jMenu6.add(jSeparator2);

              DeleteBookMenuButton2.setText("Delete a book");
              DeleteBookMenuButton2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DeleteBookMenuButton2ActionPerformed(evt);
                     }
              });
              jMenu6.add(DeleteBookMenuButton2);

              DeleteMemberMenuItem2.setText("Delete a member");
              DeleteMemberMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DeleteMemberMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(DeleteMemberMenuItem2);
              jMenu6.add(jSeparator1);

              EditBookMenuItem2.setText("Edit information of a book");
              EditBookMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            EditBookMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(EditBookMenuItem2);

              EditMemberMenuItem2.setText("Edit information of a member");
              EditMemberMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            EditMemberMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(EditMemberMenuItem2);
              jMenu6.add(jSeparator25);

              ViewBooksMenuItem2.setText("View all books");
              ViewBooksMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewBooksMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ViewBooksMenuItem2);

              ViewMembersMenuItem2.setText("View all members");
              ViewMembersMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewMembersMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ViewMembersMenuItem2);
              jMenu6.add(jSeparator26);

              ExitMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              ExitMenuItem2.setText("Exit");
              ExitMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ExitMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ExitMenuItem2);

              jMenuBar4.add(jMenu6);

              jMenu7.setText("Help");
              jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              ShortcutsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              ShortcutsMenuItem.setText("Shortcuts");
              ShortcutsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ShortcutsMenuItemActionPerformed(evt);
                     }
              });
              jMenu7.add(ShortcutsMenuItem);
              jMenu7.add(jSeparator27);

              AboutUsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              AboutUsMenuItem.setText("About us");
              AboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AboutUsMenuItemActionPerformed(evt);
                     }
              });
              jMenu7.add(AboutUsMenuItem);

              jMenuBar4.add(jMenu7);

              setJMenuBar(jMenuBar4);

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(417, 417, 417))
                     .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(jLabel4)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                          .addComponent(jLabel3)
                                          .addGap(0, 10, Short.MAX_VALUE))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                 .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                               .addComponent(SearchTermLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                                               .addComponent(DateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                               .addComponent(DateBox, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                               .addComponent(SearchTermBox))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                               .addComponent(GetIssuesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                               .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                               .addComponent(MenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                               .addComponent(ExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addGroup(layout.createSequentialGroup()
                                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                             .addComponent(MemberNameRadioButton)
                                                                             .addGroup(layout.createSequentialGroup()
                                                                                    .addComponent(DateRadioButton)
                                                                                    .addGap(29, 29, 29)
                                                                                    .addComponent(BookNameRadioButton)))
                                                                      .addGap(8, 8, 8))
                                                               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                             .addGroup(layout.createSequentialGroup()
                                                                                    .addGap(124, 124, 124)
                                                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addGap(18, 18, 18)
                                                                                    .addComponent(GroupByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                             .addGroup(layout.createSequentialGroup()
                                                                                    .addGap(112, 112, 112)
                                                                                    .addComponent(TotalCopiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                    .addComponent(TotalCopiesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                      .addGap(0, 0, Short.MAX_VALUE))))
                                                 .addComponent(jScrollPane1))
                                          .addGap(34, 34, 34))))
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 8, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(GetIssuesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(DateRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(BookNameRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(SearchTermLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(SearchTermBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createSequentialGroup()
                                          .addComponent(MemberNameRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(TotalCopiesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(TotalCopiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addComponent(GroupByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel3)
                                   .addComponent(jLabel4)))
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void DateRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateRadioButtonActionPerformed
              JRadioButton rb = (JRadioButton)evt.getSource();
              DefaultTableModel model = (DefaultTableModel)ResultTable.getModel();
              
              if (rb.isSelected()){
                     
                     model.setRowCount(0);
                     
                     SearchTermBox.setText("");
                     DateBox.setText("");
                     
                     TotalCopiesBox.setVisible(false);
                     TotalCopiesLabel.setVisible(false);
                     SearchTermBox.setEnabled(false);
                     SearchTermLabel.setEnabled(false);
                     DateBox.setEnabled(true);
                     DateLabel.setEnabled(true);
                                          
                     GroupByCombo.setSelectedIndex(0);
                     
                     DateBox.requestFocusInWindow();

              }
       }//GEN-LAST:event_DateRadioButtonActionPerformed

       private void BookNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNameRadioButtonActionPerformed
              JRadioButton rb = (JRadioButton)evt.getSource();
              DefaultTableModel model = (DefaultTableModel)ResultTable.getModel();
              
              if (rb.isSelected()){
                     
                     model.setRowCount(0);
                     
                     SearchTermBox.setText("");
                     DateBox.setText("");
                     
                     TotalCopiesBox.setVisible(false);
                     TotalCopiesLabel.setVisible(false);
                     SearchTermBox.setEnabled(true);
                     SearchTermLabel.setEnabled(true);
                     DateBox.setEnabled(false);
                     DateLabel.setEnabled(false);
                     
                     SearchTermBox.requestFocusInWindow();
                     
                     GroupByCombo.setSelectedIndex(0);
              }
       }//GEN-LAST:event_BookNameRadioButtonActionPerformed

       private void MemberNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberNameRadioButtonActionPerformed
              JRadioButton rb = (JRadioButton)evt.getSource();
              DefaultTableModel model = (DefaultTableModel)ResultTable.getModel();
              
              if (rb.isSelected()){
                     
                     model.setRowCount(0);
                     
                     SearchTermBox.setText("");
                     DateBox.setText("");
                     
                     TotalCopiesBox.setVisible(false);
                     TotalCopiesLabel.setVisible(false);
                     SearchTermBox.setEnabled(true);
                     SearchTermLabel.setEnabled(true);
                     DateBox.setEnabled(false);
                     DateLabel.setEnabled(false);
                     
                     SearchTermBox.requestFocusInWindow();
                     
                     GroupByCombo.setSelectedIndex(0);
              }
       }//GEN-LAST:event_MemberNameRadioButtonActionPerformed

       private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
              System.exit(0);
       }//GEN-LAST:event_ExitButtonActionPerformed

       private void GetIssuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetIssuesButtonActionPerformed
              DefaultTableModel model = (DefaultTableModel)ResultTable.getModel();
              
              model.setRowCount(0);
              
              int c = 0;
              int totalCopies = 0;
              int index = GroupByCombo.getSelectedIndex();
              
              try{
                     
                     Class.forName("com.mysql.jdbc.Driver");
                     Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "password");
                     
                     Statement stmt = con.createStatement();
                     
                     String query = "";
                     
                     if (DateRadioButton.isSelected()){
                            
                            
                            if (!DateBox.getText().equals("")){
                                   
                                   String doi = DateBox.getText().substring(6, 10) + "-" + DateBox.getText().substring(3, 5) + "-" + DateBox.getText().substring(0, 2);
                                   
                                   switch(index){
                                          
                                          case 0:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where dateofIssue =  '" + doi + "' order by bookNo;";
                                                 break;
                                                 
                                          case 1:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where dateofIssue =  '" + doi + "' order by bookName;";
                                                 break;
                                                 
                                          case 2:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where dateofIssue =  '" + doi + "' order by memberNo;";
                                                 break;
                                                 
                                          case 3:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where dateofIssue =  '" + doi + "' order by memberName;";
                                                 break;
                                                 
                                          case 4:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where dateofIssue =  '" + doi + "' order by noOfCopies;";
                                                 break;
                                                 
                                          case 5:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where dateofIssue =  '" + doi + "' order by dateofIssue;";
                                                 break;
                                   }
                                   
                                   ResultSet rs = stmt.executeQuery(query);
                                   
                                   while (rs.next()){
                                          
                                          c = 1;
                                          totalCopies += rs.getInt(6);
                                          model.addRow(new Object[] {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
                                   }
                                   
                                   if (c != 1){
                                          JOptionPane.showMessageDialog(null, "No books were issued on this date.");
                                   }
                                   
                                   else{
                                          
                                          TotalCopiesBox.setVisible(true);
                                          TotalCopiesLabel.setVisible(true);
                                   
                                          TotalCopiesBox.setText(Integer.toString(totalCopies));
                                          TotalCopiesLabel.setText("Total books issued on date: ");
                                   }
                                   rs.close();
                            }
                            else{
                                   
                                   JOptionPane.showMessageDialog(null, "Please enter a value in the box.");
                            }
                     }
                     else if (SearchTermBox.isEnabled() && !SearchTermBox.getText().equals("")){
                            
                            int k = 0;
                            
                            if (BookNameRadioButton.isSelected()){
                                   
                                   k = 1;
                                   
                                   switch (index) {
                                          case 0:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where bookName like  '%%" + SearchTermBox.getText() + "%%' order by bookNo;";
                                                 break;
                                                 
                                          case 1:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where bookName like  '%%" + SearchTermBox.getText() + "%%' order by bookName;";
                                                 break;
                                                 
                                          case 2:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where bookName like  '%%" + SearchTermBox.getText() + "%%' order by memberNo;";
                                                 break;
                                                 
                                          case 3:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where bookName like  '%%" + SearchTermBox.getText() + "%%' order by memberName;";
                                                 break;
                                                 
                                          case 4:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where bookName like  '%%" + SearchTermBox.getText() + "%%' order by noOfCopies;";
                                                 break;
                                                 
                                          default:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where bookName like  '%%" + SearchTermBox.getText() + "%%' order by dateofIssue;";
                                                 break;
                                   }
                            }
                            else if (MemberNameRadioButton.isSelected()){
                                   
                                   k = 2;
                                   
                                   switch (index) {
                                          
                                          case 0:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where memberName like  '%%" + SearchTermBox.getText() + "%%' order by bookNo;";
                                                 break;
                                                 
                                          case 1:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where memberName like  '%%" + SearchTermBox.getText() + "%%' order by bookName;";
                                                 break;
                                                 
                                          case 2:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where memberName like  '%%" + SearchTermBox.getText() + "%%' order by memberNo;";
                                                 break;
                                                 
                                          case 3:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where memberName like  '%%" + SearchTermBox.getText() + "%%' order by memberName;";
                                                 break;
                                                 
                                          case 4:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where memberName like  '%%" + SearchTermBox.getText() + "%%' order by noOfCopies;";
                                                 break;
                                                 
                                          default:
                                                 query = "select bookNo, bookName, memberNo, memberName, DATE_FORMAT(dateOfIssue, '%d-%m-%y'), noOfCopies from issues where memberName like  '%%" + SearchTermBox.getText() + "%%' order by dateofIssue;";
                                                 break;
                                   }
                            }
                            
                            ResultSet rs = stmt.executeQuery(query);
                            
                            while (rs.next()){
                                   
                                   c = 1;
                                   totalCopies += rs.getInt(6);
                                   model.addRow(new Object[] {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});
                            }
                            
                            if (c != 1){
                                   JOptionPane.showMessageDialog(null, "No books were issued or the data entered has mistakes.");
                            }
                            else{
                                   
                                   if (k == 1){
                                          
                                          TotalCopiesLabel.setVisible(true);
                                          TotalCopiesBox.setVisible(true);
                                          
                                          TotalCopiesLabel.setText("Total copies issued of book: ");
                                          TotalCopiesBox.setText(Integer.toString(totalCopies));
                                   }
                                   else{
                                          
                                          TotalCopiesLabel.setVisible(true);
                                          TotalCopiesBox.setVisible(true);
                                          
                                          TotalCopiesLabel.setText("Total copies issued by member(s): ");
                                          TotalCopiesBox.setText(Integer.toString(totalCopies));
                                   }         
                            }
                     }
                     else{
                            
                            if (!DateRadioButton.isSelected() && !BookNameRadioButton.isSelected() && !MemberNameRadioButton.isSelected()){
                                   
                                   JOptionPane.showMessageDialog(null, "Please select a radio button.");
                            }
                            else{
                                   
                                   JOptionPane.showMessageDialog(null, "Please enter a value in the box.");
                            }
                     }
                     
                     stmt.close();
                     con.close();
              }
              catch(Exception e){
                     JOptionPane.showMessageDialog(null, "A databse connection error occured.");
              }
       }//GEN-LAST:event_GetIssuesButtonActionPerformed

       private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
              DefaultTableModel model = (DefaultTableModel)ResultTable.getModel();
              model.setRowCount(0);
              
              DateBox.setText("");
              SearchTermBox.setText("");
              TotalCopiesBox.setText("");
              
              DateBox.setEnabled(false);
              DateLabel.setEnabled(false);
              SearchTermBox.setEnabled(false);
              SearchTermLabel.setEnabled(false);
              
              TotalCopiesLabel.setVisible(false);
              TotalCopiesBox.setVisible(false);
              
              buttonGroup1.clearSelection();
              GroupByCombo.setSelectedIndex(0);
       }//GEN-LAST:event_ClearButtonActionPerformed

       private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
              this.setVisible(false);
              MainPage page = new MainPage();
              page.setVisible(true);
       }//GEN-LAST:event_MenuButtonActionPerformed

       private void DateBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateBoxKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     GetIssuesButton.doClick();
              }
       }//GEN-LAST:event_DateBoxKeyPressed

       private void SearchTermBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTermBoxKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     GetIssuesButton.doClick();
              }
       }//GEN-LAST:event_SearchTermBoxKeyPressed

       private void GroupByComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GroupByComboKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     GetIssuesButton.doClick();
              }
       }//GEN-LAST:event_GroupByComboKeyPressed

       private void AddBookMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookMenuItem3ActionPerformed
              this.setVisible(false);
              AddBook books = new AddBook();
              books.setVisible(true);
       }//GEN-LAST:event_AddBookMenuItem3ActionPerformed

       private void AddMemberMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemberMenuItem2ActionPerformed
              this.setVisible(false);
              AddMember member = new AddMember();
              member.setVisible(true);
       }//GEN-LAST:event_AddMemberMenuItem2ActionPerformed

       private void IssueBookMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookMenuItem2ActionPerformed
              this.setVisible(false);
              IssueBook issues = new IssueBook();
              issues.setVisible(true);
       }//GEN-LAST:event_IssueBookMenuItem2ActionPerformed

       private void ReturnBookMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookMenuItem2ActionPerformed
              this.setVisible(false);
              ReturnBook returns = new ReturnBook();
              returns.setVisible(true);
       }//GEN-LAST:event_ReturnBookMenuItem2ActionPerformed

       private void SearchBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookMenuItemActionPerformed
             this.setVisible(false);
             SearchBook search  = new SearchBook();
             search.setVisible(true);
       }//GEN-LAST:event_SearchBookMenuItemActionPerformed

       private void ViewReturnsMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReturnsMenuItem2ActionPerformed
              this.setVisible(false);
              ViewReturns returns = new ViewReturns();
              returns.setVisible(true);
       }//GEN-LAST:event_ViewReturnsMenuItem2ActionPerformed

       private void ViewPurchasesMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPurchasesMenuItem2ActionPerformed
              this.setVisible(false);
              ViewPurchases purchase = new ViewPurchases();
              purchase.setVisible(true);
       }//GEN-LAST:event_ViewPurchasesMenuItem2ActionPerformed

       private void DeleteBookMenuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookMenuButton2ActionPerformed
              this.setVisible(false);
              DeleteBook deleteBook = new DeleteBook();
              deleteBook.setVisible(true);
       }//GEN-LAST:event_DeleteBookMenuButton2ActionPerformed

       private void DeleteMemberMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMemberMenuItem2ActionPerformed
              this.setVisible(false);
              new DeleteMember().setVisible(true);
       }//GEN-LAST:event_DeleteMemberMenuItem2ActionPerformed

       private void EditBookMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBookMenuItem2ActionPerformed
              this.setVisible(false);
              new EditBook().setVisible(true);
       }//GEN-LAST:event_EditBookMenuItem2ActionPerformed

       private void EditMemberMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMemberMenuItem2ActionPerformed
              this.setVisible(false);
              new EditMember().setVisible(true);
       }//GEN-LAST:event_EditMemberMenuItem2ActionPerformed

       private void ViewBooksMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksMenuItem2ActionPerformed
              this.setVisible(false);
              new ViewBooks().setVisible(true);
       }//GEN-LAST:event_ViewBooksMenuItem2ActionPerformed

       private void ViewMembersMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMembersMenuItem2ActionPerformed
              this.setVisible(false);
              new ViewMembers().setVisible(true);
       }//GEN-LAST:event_ViewMembersMenuItem2ActionPerformed

       private void ExitMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItem2ActionPerformed
              System.exit(0);
       }//GEN-LAST:event_ExitMenuItem2ActionPerformed

       private void PurchaseBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseBookMenuItemActionPerformed
              this.setVisible(false);
              PurchaseBook purchase = new PurchaseBook();
              purchase.setVisible(true);
       }//GEN-LAST:event_PurchaseBookMenuItemActionPerformed

       private void SearchMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMemberMenuItemActionPerformed
              this.setVisible(false);
              SearchMember search = new SearchMember();
              search.setVisible(true);
       }//GEN-LAST:event_SearchMemberMenuItemActionPerformed

       private void AboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuItemActionPerformed
              AboutUsPage page = new AboutUsPage();
              page.setVisible(true);
              page.setLocationRelativeTo(this);
       }//GEN-LAST:event_AboutUsMenuItemActionPerformed

       private void ShortcutsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortcutsMenuItemActionPerformed
              ShortcutsPage page = new ShortcutsPage();
              page.setVisible(true);
              page.setLocationRelativeTo(this);
       }//GEN-LAST:event_ShortcutsMenuItemActionPerformed

       private void GroupByComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupByComboActionPerformed
              JComboBox cb = (JComboBox)evt.getSource();
              
              SearchTermBox.requestFocusInWindow();
              
              if (cb.getSelectedIndex() != -1 && !SearchTermBox.getText().equals("")){
                     
                     GetIssuesButton.doClick();
              }
              else if (cb.getSelectedIndex() != -1 && !DateBox.getText().equals("")){
                     
                     GetIssuesButton.doClick();
              }
       }//GEN-LAST:event_GroupByComboActionPerformed

       /**
        * @param args the command line arguments
        */
       public static void main(String args[]) {
              /* Set the Nimbus look and feel */
              //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
              /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
               */
              try {
                     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Windows".equals(info.getName())) {
                                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                   break;
                            }
                     }
              } catch (ClassNotFoundException ex) {
                     java.util.logging.Logger.getLogger(ViewIssues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                     java.util.logging.Logger.getLogger(ViewIssues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (IllegalAccessException ex) {
                     java.util.logging.Logger.getLogger(ViewIssues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                     java.util.logging.Logger.getLogger(ViewIssues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              }
              //</editor-fold>

              /* Create and display the form */
              java.awt.EventQueue.invokeLater(new Runnable() {
                     public void run() {
                            new ViewIssues().setVisible(true);
                     }
              });
       }

       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JMenuItem AboutUsMenuItem;
       private javax.swing.JMenuItem AddBookMenuItem3;
       private javax.swing.JMenuItem AddMemberMenuItem2;
       private javax.swing.JRadioButton BookNameRadioButton;
       private javax.swing.JButton ClearButton;
       private javax.swing.JTextField DateBox;
       private javax.swing.JLabel DateLabel;
       private javax.swing.JRadioButton DateRadioButton;
       private javax.swing.JMenuItem DeleteBookMenuButton2;
       private javax.swing.JMenuItem DeleteMemberMenuItem2;
       private javax.swing.JMenuItem EditBookMenuItem2;
       private javax.swing.JMenuItem EditMemberMenuItem2;
       private javax.swing.JButton ExitButton;
       private javax.swing.JMenuItem ExitMenuItem2;
       private javax.swing.JButton GetIssuesButton;
       private javax.swing.JComboBox<String> GroupByCombo;
       private javax.swing.JMenuItem IssueBookMenuItem2;
       private javax.swing.JRadioButton MemberNameRadioButton;
       private javax.swing.JButton MenuButton;
       private javax.swing.JMenuItem PurchaseBookMenuItem;
       private javax.swing.JTable ResultTable;
       private javax.swing.JMenuItem ReturnBookMenuItem2;
       private javax.swing.JMenuItem SearchBookMenuItem;
       private javax.swing.JMenuItem SearchMemberMenuItem;
       private javax.swing.JTextField SearchTermBox;
       private javax.swing.JLabel SearchTermLabel;
       private javax.swing.JMenuItem ShortcutsMenuItem;
       private javax.swing.JTextField TotalCopiesBox;
       private javax.swing.JLabel TotalCopiesLabel;
       private javax.swing.JMenuItem ViewBooksMenuItem2;
       private javax.swing.JMenuItem ViewMembersMenuItem2;
       private javax.swing.JMenuItem ViewPurchasesMenuItem2;
       private javax.swing.JMenuItem ViewReturnsMenuItem2;
       private javax.swing.ButtonGroup buttonGroup1;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JLabel jLabel2;
       private javax.swing.JLabel jLabel3;
       private javax.swing.JLabel jLabel4;
       private javax.swing.JMenu jMenu6;
       private javax.swing.JMenu jMenu7;
       private javax.swing.JMenuBar jMenuBar4;
       private javax.swing.JScrollPane jScrollPane1;
       private javax.swing.JPopupMenu.Separator jSeparator1;
       private javax.swing.JPopupMenu.Separator jSeparator19;
       private javax.swing.JPopupMenu.Separator jSeparator2;
       private javax.swing.JPopupMenu.Separator jSeparator21;
       private javax.swing.JPopupMenu.Separator jSeparator22;
       private javax.swing.JPopupMenu.Separator jSeparator24;
       private javax.swing.JPopupMenu.Separator jSeparator25;
       private javax.swing.JPopupMenu.Separator jSeparator26;
       private javax.swing.JPopupMenu.Separator jSeparator27;
       // End of variables declaration//GEN-END:variables

       private void SetIcon() {
              
              setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
       }
}
