import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Malay Agarwal
 */
public class ViewPurchases extends javax.swing.JFrame {

       /**
        * Creates new form ViewPurchases
        */
       public ViewPurchases() {
              initComponents();
              
              this.model = (DefaultTableModel)ResultTable.getModel();
              SetIcon();
       }
       
       DefaultTableModel model;

       /**
        * This method is called from within the constructor to initialize the form.
        * WARNING: Do NOT modify this code. The content of this method is always
        * regenerated by the Form Editor.
        */
       @SuppressWarnings("unchecked")
       // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
       private void initComponents() {

              buttonGroup1 = new javax.swing.ButtonGroup();
              jScrollPane1 = new javax.swing.JScrollPane();
              ResultTable = new javax.swing.JTable();
              jLabel1 = new javax.swing.JLabel();
              DateLabel = new javax.swing.JLabel();
              DateBox = new javax.swing.JTextField();
              SearchTermLabel = new javax.swing.JLabel();
              SearchTermBox = new javax.swing.JTextField();
              GetPurchasesButton = new javax.swing.JButton();
              ClearButton = new javax.swing.JButton();
              DateRadioButton = new javax.swing.JRadioButton();
              AuthorRadioButton = new javax.swing.JRadioButton();
              PublisherRadioButton = new javax.swing.JRadioButton();
              BookNameRadioButton = new javax.swing.JRadioButton();
              MenuButton = new javax.swing.JButton();
              ExitButton = new javax.swing.JButton();
              SortByLabel = new javax.swing.JLabel();
              SortByCombo = new javax.swing.JComboBox<>();
              jLabel5 = new javax.swing.JLabel();
              jLabel3 = new javax.swing.JLabel();
              jMenuBar4 = new javax.swing.JMenuBar();
              jMenu6 = new javax.swing.JMenu();
              AddBookMenuItem3 = new javax.swing.JMenuItem();
              AddMemberMenuItem2 = new javax.swing.JMenuItem();
              jSeparator19 = new javax.swing.JPopupMenu.Separator();
              IssueBookMenuItem2 = new javax.swing.JMenuItem();
              ReturnBookMenuItem2 = new javax.swing.JMenuItem();
              PurchaseBookMenuItem = new javax.swing.JMenuItem();
              jSeparator21 = new javax.swing.JPopupMenu.Separator();
              SearchBookMenuItem = new javax.swing.JMenuItem();
              jSeparator24 = new javax.swing.JPopupMenu.Separator();
              ViewIssuesMenuItem = new javax.swing.JMenuItem();
              ViewReturnsMenuItem2 = new javax.swing.JMenuItem();
              jSeparator22 = new javax.swing.JPopupMenu.Separator();
              SearchMemberMenuItem = new javax.swing.JMenuItem();
              jSeparator2 = new javax.swing.JPopupMenu.Separator();
              DeleteBookMenuButton2 = new javax.swing.JMenuItem();
              DeleteMemberMenuItem2 = new javax.swing.JMenuItem();
              jSeparator1 = new javax.swing.JPopupMenu.Separator();
              EditBookMenuItem2 = new javax.swing.JMenuItem();
              EditMemberMenuItem2 = new javax.swing.JMenuItem();
              jSeparator25 = new javax.swing.JPopupMenu.Separator();
              ViewBooksMenuItem2 = new javax.swing.JMenuItem();
              ViewMembersMenuItem2 = new javax.swing.JMenuItem();
              jSeparator26 = new javax.swing.JPopupMenu.Separator();
              ExitMenuItem2 = new javax.swing.JMenuItem();
              jMenu7 = new javax.swing.JMenu();
              ShortcutsMenuItem = new javax.swing.JMenuItem();
              jSeparator27 = new javax.swing.JPopupMenu.Separator();
              AboutUsMenuItem = new javax.swing.JMenuItem();

              setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
              setTitle("View purchases");
              setResizable(false);

              ResultTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ResultTable.setModel(new javax.swing.table.DefaultTableModel(
                     new Object [][] {

                     },
                     new String [] {
                            "Book Number", "Book Name", "Date of Purchase", "Type", "No Of Copies", "Cost Per Copy", "Total Cost"
                     }
              ) {
                     boolean[] canEdit = new boolean [] {
                            false, false, false, true, false, false, false
                     };

                     public boolean isCellEditable(int rowIndex, int columnIndex) {
                            return canEdit [columnIndex];
                     }
              });
              jScrollPane1.setViewportView(ResultTable);

              jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
              jLabel1.setText("VIEW PURCHASES");

              DateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              DateLabel.setText("Enter date:");
              DateLabel.setEnabled(false);

              DateBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              DateBox.setEnabled(false);
              DateBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            DateBoxKeyPressed(evt);
                     }
              });

              SearchTermLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              SearchTermLabel.setText("Enter search term:");
              SearchTermLabel.setEnabled(false);

              SearchTermBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              SearchTermBox.setEnabled(false);
              SearchTermBox.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            SearchTermBoxKeyPressed(evt);
                     }
              });

              GetPurchasesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              GetPurchasesButton.setText("Get purchases");
              GetPurchasesButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            GetPurchasesButtonActionPerformed(evt);
                     }
              });

              ClearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ClearButton.setMnemonic('C');
              ClearButton.setText("Clear");
              ClearButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ClearButtonActionPerformed(evt);
                     }
              });

              buttonGroup1.add(DateRadioButton);
              DateRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              DateRadioButton.setText("Get purchases by date.");
              DateRadioButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DateRadioButtonActionPerformed(evt);
                     }
              });

              buttonGroup1.add(AuthorRadioButton);
              AuthorRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              AuthorRadioButton.setText("Get purchases by author.");
              AuthorRadioButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AuthorRadioButtonActionPerformed(evt);
                     }
              });

              buttonGroup1.add(PublisherRadioButton);
              PublisherRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              PublisherRadioButton.setText("Get purchases by publisher.");
              PublisherRadioButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            PublisherRadioButtonActionPerformed(evt);
                     }
              });

              buttonGroup1.add(BookNameRadioButton);
              BookNameRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              BookNameRadioButton.setText("Get purchases by book name.");
              BookNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            BookNameRadioButtonActionPerformed(evt);
                     }
              });

              MenuButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              MenuButton.setMnemonic('M');
              MenuButton.setText("Main menu");
              MenuButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            MenuButtonActionPerformed(evt);
                     }
              });

              ExitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              ExitButton.setText("Exit");
              ExitButton.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ExitButtonActionPerformed(evt);
                     }
              });

              SortByLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              SortByLabel.setText("Sort by:");

              SortByCombo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              SortByCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default (Book Number)", "Book Name", "Date of Purchase", "Type", "No. of Copies", "Cost/Copy", "Total Cost" }));
              SortByCombo.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SortByComboActionPerformed(evt);
                     }
              });
              SortByCombo.addKeyListener(new java.awt.event.KeyAdapter() {
                     public void keyPressed(java.awt.event.KeyEvent evt) {
                            SortByComboKeyPressed(evt);
                     }
              });

              jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
              jLabel3.setText("After entering a value in the box, click on the Get purchases button or press enter.");

              jMenu6.setText("Quick Actions");
              jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              AddBookMenuItem3.setText("Add a book");
              AddBookMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AddBookMenuItem3ActionPerformed(evt);
                     }
              });
              jMenu6.add(AddBookMenuItem3);

              AddMemberMenuItem2.setText("Add a member");
              AddMemberMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AddMemberMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(AddMemberMenuItem2);
              jMenu6.add(jSeparator19);

              IssueBookMenuItem2.setText("Issue a book");
              IssueBookMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            IssueBookMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(IssueBookMenuItem2);

              ReturnBookMenuItem2.setText("Return a book");
              ReturnBookMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ReturnBookMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ReturnBookMenuItem2);

              PurchaseBookMenuItem.setText("Purchase a book");
              PurchaseBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            PurchaseBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu6.add(PurchaseBookMenuItem);
              jMenu6.add(jSeparator21);

              SearchBookMenuItem.setText("Search for a book");
              SearchBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SearchBookMenuItemActionPerformed(evt);
                     }
              });
              jMenu6.add(SearchBookMenuItem);
              jMenu6.add(jSeparator24);

              ViewIssuesMenuItem.setText("View issues");
              ViewIssuesMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewIssuesMenuItemActionPerformed(evt);
                     }
              });
              jMenu6.add(ViewIssuesMenuItem);

              ViewReturnsMenuItem2.setText("View returns");
              ViewReturnsMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewReturnsMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ViewReturnsMenuItem2);
              jMenu6.add(jSeparator22);

              SearchMemberMenuItem.setText("Search for a member");
              SearchMemberMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            SearchMemberMenuItemActionPerformed(evt);
                     }
              });
              jMenu6.add(SearchMemberMenuItem);
              jMenu6.add(jSeparator2);

              DeleteBookMenuButton2.setText("Delete a book");
              DeleteBookMenuButton2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DeleteBookMenuButton2ActionPerformed(evt);
                     }
              });
              jMenu6.add(DeleteBookMenuButton2);

              DeleteMemberMenuItem2.setText("Delete a member");
              DeleteMemberMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            DeleteMemberMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(DeleteMemberMenuItem2);
              jMenu6.add(jSeparator1);

              EditBookMenuItem2.setText("Edit information of a book");
              EditBookMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            EditBookMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(EditBookMenuItem2);

              EditMemberMenuItem2.setText("Edit information of a member");
              EditMemberMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            EditMemberMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(EditMemberMenuItem2);
              jMenu6.add(jSeparator25);

              ViewBooksMenuItem2.setText("View all books");
              ViewBooksMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewBooksMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ViewBooksMenuItem2);

              ViewMembersMenuItem2.setText("View all members");
              ViewMembersMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ViewMembersMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ViewMembersMenuItem2);
              jMenu6.add(jSeparator26);

              ExitMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              ExitMenuItem2.setText("Exit");
              ExitMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            ExitMenuItem2ActionPerformed(evt);
                     }
              });
              jMenu6.add(ExitMenuItem2);

              jMenuBar4.add(jMenu6);

              jMenu7.setText("Help");
              jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

              ShortcutsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              ShortcutsMenuItem.setText("Shortcuts");
              jMenu7.add(ShortcutsMenuItem);
              jMenu7.add(jSeparator27);

              AboutUsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
              AboutUsMenuItem.setText("About us");
              AboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                     public void actionPerformed(java.awt.event.ActionEvent evt) {
                            AboutUsMenuItemActionPerformed(evt);
                     }
              });
              jMenu7.add(AboutUsMenuItem);

              jMenuBar4.add(jMenu7);

              setJMenuBar(jMenuBar4);

              javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
              getContentPane().setLayout(layout);
              layout.setHorizontalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                 .addComponent(SearchTermLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                 .addComponent(DateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                 .addComponent(DateBox)
                                                 .addComponent(SearchTermBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                 .addComponent(MenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                 .addComponent(GetPurchasesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                 .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addComponent(jLabel1)
                                                 .addGroup(layout.createSequentialGroup()
                                                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addGroup(layout.createSequentialGroup()
                                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                             .addComponent(AuthorRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                             .addComponent(DateRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                      .addGap(18, 18, 18)
                                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                             .addComponent(BookNameRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                             .addComponent(PublisherRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                               .addGroup(layout.createSequentialGroup()
                                                                      .addGap(37, 37, 37)
                                                                      .addComponent(SortByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                      .addGap(18, 18, 18)
                                                                      .addComponent(SortByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                          .addGap(0, 0, Short.MAX_VALUE)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel3))
                                                 .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 34, Short.MAX_VALUE))
              );
              layout.setVerticalGroup(
                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(GetPurchasesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(SearchTermLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(SearchTermBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                 .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                                 .addComponent(MenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                          .addGap(27, 27, 27)
                                          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                          .addGap(18, 18, 18)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(14, 14, 14))
                                                 .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                   .addGroup(layout.createSequentialGroup()
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(DateRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(BookNameRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGap(11, 11, 11)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                 .addComponent(PublisherRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(AuthorRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                          .addGap(11, 11, 11)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                 .addComponent(SortByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addComponent(SortByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
              );

              pack();
       }// </editor-fold>//GEN-END:initComponents

       private void BookNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNameRadioButtonActionPerformed
              JRadioButton rb = (JRadioButton)evt.getSource();
              
               if (rb.isSelected()){
                      
                      DateLabel.setEnabled(false);
                      DateBox.setEnabled(false);
                      SearchTermLabel.setEnabled(true);
                      SearchTermBox.setEnabled(true);
                      
                      DateBox.setText("");
                      SearchTermBox.setText("");
                      
                      SearchTermBox.requestFocusInWindow();
                      
                      model.setRowCount(0);
                      SortByCombo.setSelectedIndex(0); 
               }
       }//GEN-LAST:event_BookNameRadioButtonActionPerformed

       private void AuthorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorRadioButtonActionPerformed
              JRadioButton rb = (JRadioButton)evt.getSource();
              
               if (rb.isSelected()){
                      
                      DateLabel.setEnabled(false);
                      DateBox.setEnabled(false);
                      SearchTermLabel.setEnabled(true);
                      SearchTermBox.setEnabled(true);
                      
                      DateBox.setText("");
                      SearchTermBox.setText("");
                      
                      SearchTermBox.requestFocusInWindow();
                      
                      model.setRowCount(0);
                      SortByCombo.setSelectedIndex(0); 
               }
       }//GEN-LAST:event_AuthorRadioButtonActionPerformed

       private void PublisherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublisherRadioButtonActionPerformed
              JRadioButton rb = (JRadioButton)evt.getSource();
              
               if (rb.isSelected()){
                      
                      DateLabel.setEnabled(false);
                      DateBox.setEnabled(false);
                      SearchTermLabel.setEnabled(true);
                      SearchTermBox.setEnabled(true);
                      
                      DateBox.setText("");
                      SearchTermBox.setText("");
                      
                      SearchTermBox.requestFocusInWindow();
                      
                      model.setRowCount(0);
                      SortByCombo.setSelectedIndex(0); 
               }
       }//GEN-LAST:event_PublisherRadioButtonActionPerformed

       private void DateRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateRadioButtonActionPerformed
              JRadioButton rb = (JRadioButton)evt.getSource();
              
               if (rb.isSelected()){
                      
                      DateLabel.setEnabled(true);
                      DateBox.setEnabled(true);
                      SearchTermLabel.setEnabled(false);
                      SearchTermBox.setEnabled(false);
                      
                      DateBox.setText("");
                      SearchTermBox.setText("");
                      
                      model.setRowCount(0);
                      SortByCombo.setSelectedIndex(0); 
                      
                      DateBox.requestFocusInWindow();
               }
       }//GEN-LAST:event_DateRadioButtonActionPerformed

       private void GetPurchasesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetPurchasesButtonActionPerformed
              model.setRowCount(0);
              
              int c = 0;
              int index = SortByCombo.getSelectedIndex();
              
              try{
                     
                     Class.forName("com.mysql.jdbc.Driver");
                     Connection con = DriverManager.getConnection("jdbc:mysql://localhost/library", "root", "password");
                     
                     Statement stmt = con.createStatement();
                     String query = "";
                     
                     if (DateRadioButton.isSelected() && !DateBox.getText().equals("")){
                            
                            String dop = DateBox.getText().substring(6, 10) + "-" + DateBox.getText().substring(3, 5) + "-" + DateBox.getText().substring(0, 2);
                            
                            switch (index){
                                   
                                   case 0:
                                          query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where dateOfPurchase = '" + dop + "' order by bookNo;";
                                          break;
                                   
                                   case 1:
                                          query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where dateOfPurchase = '" + dop + "' order by bookName;";
                                          break;
                                   
                                   case 2:
                                          query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where dateOfPurchase = '" + dop + "' order by dateOfPurchase";
                                          break;
                                   
                                   case 3:
                                          query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where dateOfPurchase = '" + dop + "' order by type;";
                                          break;
                                   
                                   case 4:
                                          query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where dateOfPurchase = '" + dop + "' order by noOfCopies;";
                                          break;
                                   
                                   case 5:
                                          query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where dateOfPurchase = '" + dop + "' order by costPerCopy;";
                                          break;
                                   
                                   default:
                                          query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where dateOfPurchase = '" + dop + "' order by totalCost;";
                                          break;
                            }
                            
                            ResultSet rs = stmt.executeQuery(query);
                            
                            while (rs.next()){
                                   
                                   c = 1;
                                   model.addRow(new Object[] {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
                            }
                            
                            if (c != 1){
                                   
                                   JOptionPane.showMessageDialog(null, "No books were purchased on this date.");
                            }
                            
                            rs.close();
                     }
                     else if (SearchTermBox.isEnabled() && !SearchTermBox.getText().equals("")){
                            
                            if (BookNameRadioButton.isSelected()){
                                   
                                   switch (index){
                                          
                                          case 0:
                                                 query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where bookName like '%%" + SearchTermBox.getText() + "%%' order by bookNo;";
                                                 break;
                                                 
                                          case 1:
                                                 query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where bookName like '%%" + SearchTermBox.getText() + "%%' order by bookName;";
                                                 break;
                                                 
                                          case 2:
                                                 query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where bookName like '%%" + SearchTermBox.getText() + "%%' order by dateOfPurchase;";
                                                 break;
                                                 
                                          case 3:
                                                 query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where bookName like '%%" + SearchTermBox.getText() + "%%' order by type;";
                                                 break;
                                                 
                                          case 4:
                                                 query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where bookName like '%%" + SearchTermBox.getText() + "%%' order by noOfCopies;";
                                                 break;
                                                 
                                          case 5:
                                                 query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where bookName like '%%" + SearchTermBox.getText() + "%%' order by costPerCopy;";
                                                 break;
                                                 
                                          default:
                                                 query = "select bookNo, bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases where bookName like '%%" + SearchTermBox.getText() + "%%' order by totalCost;";
                                                 break;
                                   }
                            }
                            else if (AuthorRadioButton.isSelected()){
                                   
                                   switch (index){
                                          
                                          case 0:
                                                query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.author like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by purchases.bookNo;";
                                                 break;
                                                 
                                          case 1:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.author like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by purchases.bookName;";
                                                 break;
                                                 
                                          case 2:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.author like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by dateOfPurchase;";
                                                 break;
                                                 
                                          case 3:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.author like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by type;";
                                                 break;
                                                 
                                          case 4:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.author like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by noOfCopies;";
                                                 break;
                                                 
                                          case 5:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.author like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by costPerCopy;";
                                                 break;
                                                 
                                          default:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.author like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by totalCost;";
                                                 break;
                                   }
                            }
                            else{
                                   
                                   switch (index){
                                          
                                          case 0:
                                                query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.publisher like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by purchases.bookNo;";
                                                 break;
                                                 
                                          case 1:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.publisher like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by purchases.bookName;";
                                                 break;
                                                 
                                          case 2:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.publisher like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by dateOfPurchase;";
                                                 break;
                                                 
                                          case 3:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.publisher like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by type;";
                                                 break;
                                                 
                                          case 4:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.publisher like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by noOfCopies;";
                                                 break;
                                                 
                                          case 5:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.publisher like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by costPerCopy;";
                                                 break;
                                                 
                                          default:
                                                 query = "select purchases.bookNo, purchases.bookName, DATE_FORMAT(dateOfPurchase, '%d-%m-%y'), type, noOfCopies, costPerCopy, totalCost from purchases, books where books.publisher like '%%" + SearchTermBox.getText() + "%%' and books.bookNo = purchases.bookNo order by totalCost;";
                                                 break;
                                   }
                            }
                            
                            ResultSet rs= stmt.executeQuery(query);
                            
                            while (rs.next()){
                                   
                                   c = 1;
                                   model.addRow(new Object[] {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
                            }
                            
                            if (c != 1){
                                   
                                   JOptionPane.showMessageDialog(null, "No books were purchased or the data entered has mistakes.");
                            }
                     }
                     else{
                            
                            if (!BookNameRadioButton.isSelected() && !AuthorRadioButton.isSelected() && !PublisherRadioButton.isSelected() && !DateRadioButton.isSelected()){
                                   
                                   JOptionPane.showMessageDialog(null, "Please select a radio button.");
                            }
                            else{
                                   
                                   JOptionPane.showMessageDialog(null, "Please enter a value in the box.");
                            }
                     }
                     
                     stmt.close();
                     con.close();
                     
              }
              catch(Exception e){
                     
                     JOptionPane.showMessageDialog(null, "A database connection error occured.");
              }
       }//GEN-LAST:event_GetPurchasesButtonActionPerformed

       private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
              DateLabel.setEnabled(false);
              DateBox.setEnabled(false);
              SearchTermLabel.setEnabled(false);
              SearchTermBox.setEnabled(false);
              
              DateBox.setText("");
              SearchTermBox.setText("");
              
              buttonGroup1.clearSelection();
              
              model.setRowCount(0);
              SortByCombo.setSelectedIndex(7);
       }//GEN-LAST:event_ClearButtonActionPerformed

       private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
              this.setVisible(false);
              MainPage page = new MainPage();
              page.setVisible(true);
       }//GEN-LAST:event_MenuButtonActionPerformed

       private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
              System.exit(0);
       }//GEN-LAST:event_ExitButtonActionPerformed

       private void DateBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateBoxKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     GetPurchasesButton.doClick();
              }
       }//GEN-LAST:event_DateBoxKeyPressed

       private void SearchTermBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTermBoxKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     GetPurchasesButton.doClick();
              }
       }//GEN-LAST:event_SearchTermBoxKeyPressed

       private void SortByComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SortByComboKeyPressed
              if (evt.getKeyCode() == KeyEvent.VK_ENTER){
                     
                     GetPurchasesButton.doClick();
              }
       }//GEN-LAST:event_SortByComboKeyPressed

       private void AddBookMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookMenuItem3ActionPerformed
              this.setVisible(false);
              AddBook books = new AddBook();
              books.setVisible(true);
       }//GEN-LAST:event_AddBookMenuItem3ActionPerformed

       private void AddMemberMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMemberMenuItem2ActionPerformed
              this.setVisible(false);
              AddMember member = new AddMember();
              member.setVisible(true);
       }//GEN-LAST:event_AddMemberMenuItem2ActionPerformed

       private void IssueBookMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookMenuItem2ActionPerformed
              this.setVisible(false);
              IssueBook issues = new IssueBook();
              issues.setVisible(true);
       }//GEN-LAST:event_IssueBookMenuItem2ActionPerformed

       private void ReturnBookMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookMenuItem2ActionPerformed
              this.setVisible(false);
              ReturnBook returns = new ReturnBook();
              returns.setVisible(true);
       }//GEN-LAST:event_ReturnBookMenuItem2ActionPerformed

       private void PurchaseBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseBookMenuItemActionPerformed
              this.setVisible(false);
              PurchaseBook purchase = new PurchaseBook();
              purchase.setVisible(true);
       }//GEN-LAST:event_PurchaseBookMenuItemActionPerformed

       private void SearchBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBookMenuItemActionPerformed
              this.setVisible(false);
              SearchBook search  = new SearchBook();
              search.setVisible(true);
       }//GEN-LAST:event_SearchBookMenuItemActionPerformed

       private void ViewReturnsMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewReturnsMenuItem2ActionPerformed
              this.setVisible(false);
              ViewReturns returns = new ViewReturns();
              returns.setVisible(true);
       }//GEN-LAST:event_ViewReturnsMenuItem2ActionPerformed

       private void SearchMemberMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMemberMenuItemActionPerformed
              this.setVisible(false);
              SearchMember search = new SearchMember();
              search.setVisible(true);
       }//GEN-LAST:event_SearchMemberMenuItemActionPerformed

       private void DeleteBookMenuButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBookMenuButton2ActionPerformed
              this.setVisible(false);
              DeleteBook deleteBook = new DeleteBook();
              deleteBook.setVisible(true);
       }//GEN-LAST:event_DeleteBookMenuButton2ActionPerformed

       private void DeleteMemberMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMemberMenuItem2ActionPerformed
              this.setVisible(false);
              new DeleteMember().setVisible(true);
       }//GEN-LAST:event_DeleteMemberMenuItem2ActionPerformed

       private void EditBookMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBookMenuItem2ActionPerformed
              this.setVisible(false);
              new EditBook().setVisible(true);
       }//GEN-LAST:event_EditBookMenuItem2ActionPerformed

       private void EditMemberMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMemberMenuItem2ActionPerformed
              this.setVisible(false);
              new EditMember().setVisible(true);
       }//GEN-LAST:event_EditMemberMenuItem2ActionPerformed

       private void ViewBooksMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksMenuItem2ActionPerformed
              this.setVisible(false);
              new ViewBooks().setVisible(true);
       }//GEN-LAST:event_ViewBooksMenuItem2ActionPerformed

       private void ViewMembersMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMembersMenuItem2ActionPerformed
              this.setVisible(false);
              new ViewMembers().setVisible(true);
       }//GEN-LAST:event_ViewMembersMenuItem2ActionPerformed

       private void ExitMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItem2ActionPerformed
              System.exit(0);
       }//GEN-LAST:event_ExitMenuItem2ActionPerformed

       private void ViewIssuesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewIssuesMenuItemActionPerformed
              this.setVisible(false);
              ViewIssues issues = new ViewIssues();
              issues.setVisible(true);
       }//GEN-LAST:event_ViewIssuesMenuItemActionPerformed

       private void AboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuItemActionPerformed
              AboutUsPage page = new AboutUsPage();
              page.setVisible(true);
              page.setLocationRelativeTo(this);
       }//GEN-LAST:event_AboutUsMenuItemActionPerformed

       private void SortByComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortByComboActionPerformed
              JComboBox cb = (JComboBox)evt.getSource();
              
              SearchTermBox.requestFocusInWindow();
              
              if (cb.getSelectedIndex() != -1 && !SearchTermBox.getText().equals("")){
                     
                     GetPurchasesButton.doClick();
              }
              else if (cb.getSelectedIndex() != -1 && !DateBox.getText().equals("")){
                     
                     GetPurchasesButton.doClick();
              }
       }//GEN-LAST:event_SortByComboActionPerformed

       /**
        * @param args the command line arguments
        */
       public static void main(String args[]) {
              /* Set the Nimbus look and feel */
              //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
              /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
               */
              try {
                     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Windows".equals(info.getName())) {
                                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                   break;
                            }
                     }
              } catch (ClassNotFoundException ex) {
                     java.util.logging.Logger.getLogger(ViewPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                     java.util.logging.Logger.getLogger(ViewPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (IllegalAccessException ex) {
                     java.util.logging.Logger.getLogger(ViewPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                     java.util.logging.Logger.getLogger(ViewPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
              }
              //</editor-fold>

              /* Create and display the form */
              java.awt.EventQueue.invokeLater(new Runnable() {
                     public void run() {
                            new ViewPurchases().setVisible(true);
                     }
              });
       }

       // Variables declaration - do not modify//GEN-BEGIN:variables
       private javax.swing.JMenuItem AboutUsMenuItem;
       private javax.swing.JMenuItem AddBookMenuItem3;
       private javax.swing.JMenuItem AddMemberMenuItem2;
       private javax.swing.JRadioButton AuthorRadioButton;
       private javax.swing.JRadioButton BookNameRadioButton;
       private javax.swing.JButton ClearButton;
       private javax.swing.JTextField DateBox;
       private javax.swing.JLabel DateLabel;
       private javax.swing.JRadioButton DateRadioButton;
       private javax.swing.JMenuItem DeleteBookMenuButton2;
       private javax.swing.JMenuItem DeleteMemberMenuItem2;
       private javax.swing.JMenuItem EditBookMenuItem2;
       private javax.swing.JMenuItem EditMemberMenuItem2;
       private javax.swing.JButton ExitButton;
       private javax.swing.JMenuItem ExitMenuItem2;
       private javax.swing.JButton GetPurchasesButton;
       private javax.swing.JMenuItem IssueBookMenuItem2;
       private javax.swing.JButton MenuButton;
       private javax.swing.JRadioButton PublisherRadioButton;
       private javax.swing.JMenuItem PurchaseBookMenuItem;
       private javax.swing.JTable ResultTable;
       private javax.swing.JMenuItem ReturnBookMenuItem2;
       private javax.swing.JMenuItem SearchBookMenuItem;
       private javax.swing.JMenuItem SearchMemberMenuItem;
       private javax.swing.JTextField SearchTermBox;
       private javax.swing.JLabel SearchTermLabel;
       private javax.swing.JMenuItem ShortcutsMenuItem;
       private javax.swing.JComboBox<String> SortByCombo;
       private javax.swing.JLabel SortByLabel;
       private javax.swing.JMenuItem ViewBooksMenuItem2;
       private javax.swing.JMenuItem ViewIssuesMenuItem;
       private javax.swing.JMenuItem ViewMembersMenuItem2;
       private javax.swing.JMenuItem ViewReturnsMenuItem2;
       private javax.swing.ButtonGroup buttonGroup1;
       private javax.swing.JLabel jLabel1;
       private javax.swing.JLabel jLabel3;
       private javax.swing.JLabel jLabel5;
       private javax.swing.JMenu jMenu6;
       private javax.swing.JMenu jMenu7;
       private javax.swing.JMenuBar jMenuBar4;
       private javax.swing.JScrollPane jScrollPane1;
       private javax.swing.JPopupMenu.Separator jSeparator1;
       private javax.swing.JPopupMenu.Separator jSeparator19;
       private javax.swing.JPopupMenu.Separator jSeparator2;
       private javax.swing.JPopupMenu.Separator jSeparator21;
       private javax.swing.JPopupMenu.Separator jSeparator22;
       private javax.swing.JPopupMenu.Separator jSeparator24;
       private javax.swing.JPopupMenu.Separator jSeparator25;
       private javax.swing.JPopupMenu.Separator jSeparator26;
       private javax.swing.JPopupMenu.Separator jSeparator27;
       // End of variables declaration//GEN-END:variables

       private void SetIcon() {
              
              setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
       }
}
